/*
 FusionCharts JavaScript Library
 Copyright FusionCharts Technologies LLP
 License Information at <http://www.fusioncharts.com/license>

 @author FusionCharts Technologies LLP
 @version fusioncharts/3.2.4-sr1.9888
*/
FusionCharts(["private","modules.renderer.highcharts-charts",function(){function ua(a){a=(a||0)%oa;return a<0?oa+a:a}function La(a,d){return a<=V?a:d<=V?d:d>a?0:d}function Ua(a,d){var b=d-a;return b<0?oa-b:b}function Ea(a,d,b,c,g,j,e,f,k,l){if(typeof a==="object")d=a.y,b=a.r,c=a.innerR,g=a.radiusYFactor,j=a.depth,e=a.seriesGroup,f=a.renderer,a=a.x;if(g<0||g>=1)g=0.6;a=a||0;d=d||0;b=b||1;c=c||0;j=j||0;this.renderer=f;this.hasOnePoint=k;this.use3DLighting=l;this.cx=a;this.cy=d;this.rx=b;this.ry=b*g;
this.radiusYFactor=g;this.isDoughnut=c>0;this.innerRx=c;this.innerRy=c*g;this.depth=j;this.leftX=a-b;this.rightX=a+b;this.leftInnerX=a-c;this.rightInnerX=a+c;this.depthY=d+j;this.topY=d-this.ry;this.bottomY=this.depthY+this.ry;this.bottomBorderGroup=f.g("bottom-border").add(e).translate(0,j);this.outerBackGroup=f.g("outer-back-Side").add(e);this.slicingWallsBackGroup=f.g("slicingWalls-back-Side").add(e);this.innerBackGroup=f.g("inner-back-Side").add(e);this.innerFrontGroup=f.g("inner-front-Side").add(e);
this.slicingWallsFrontGroup=f.g("slicingWalls-front-Side").add(e);this.topGroup=f.g("top-Side").add(e);this.moveCmdArr=[O];this.lineCmdArr=[J];this.closeCmdArr=[M];this.centerPoint=[a,d];this.leftPoint=[this.leftX,d];this.topPoint=[a,this.topY];this.rightPoint=[this.rightX,d];this.bottomPoint=[a,d+this.ry];this.leftDepthPoint=[this.leftX,this.depthY];this.rightDepthPoint=[this.rightX,this.depthY];this.leftInnerPoint=[this.leftInnerX,d];this.rightInnerPoint=[this.rightInnerX,d];this.leftInnerDepthPoint=
[this.leftInnerX,this.depthY];this.rightInnerDepthPoint=[this.rightInnerX,this.depthY];this.pointElemStore=[];this.slicingWallsArr=[];a=[ea,this.rx,this.ry,0,0,1,this.rightX,d];b=[ea,this.rx,this.ry,0,0,1,this.leftX,d];c=[ea,this.rx,this.ry,0,0,0,this.rightX,this.depthY];g=[ea,this.rx,this.ry,0,0,0,this.leftX,this.depthY];j=[ea,this.innerRx,this.innerRy,0,0,0,this.rightInnerX,d];d=[ea,this.innerRx,this.innerRy,0,0,0,this.leftInnerX,d];e=[ea,this.innerRx,this.innerRy,0,0,1,this.rightInnerX,this.depthY];
f=[ea,this.innerRx,this.innerRy,0,0,1,this.leftInnerX,this.depthY];this.isDoughnut?(this.topBorderPath=this.moveCmdArr.concat(this.leftPoint,a,b,this.moveCmdArr,this.leftInnerPoint,j,d),this.topPath=this.moveCmdArr.concat(this.leftPoint,a,b,this.lineCmdArr,this.leftInnerPoint,j,d,this.closeCmdArr),this.innerFrontPath=this.moveCmdArr.concat(this.leftInnerPoint,j,this.lineCmdArr,this.rightInnerDepthPoint,f,this.closeCmdArr),this.innerBackPath=this.moveCmdArr.concat(this.rightInnerPoint,d,this.lineCmdArr,
this.leftInnerDepthPoint,e,this.closeCmdArr)):this.topBorderPath=this.topPath=this.moveCmdArr.concat(this.leftPoint,a,b,this.closeCmdArr);this.outerBackPath=this.moveCmdArr.concat(this.leftPoint,a,this.lineCmdArr,this.rightDepthPoint,g,this.closeCmdArr);this.outerFrontPath=this.moveCmdArr.concat(this.rightPoint,b,this.lineCmdArr,this.leftDepthPoint,c,this.closeCmdArr);this.clipPathforOuter=[O,this.leftX,this.topY,J,this.rightX,this.topY,this.rightX,this.bottomY,this.leftX,this.bottomY,M];this.clipPathforInner=
[O,this.leftInnerX,this.topY,J,this.rightInnerX,this.topY,this.rightInnerX,this.bottomY,this.leftInnerX,this.bottomY,M];this.clipPathforNoClip=[O,this.leftInnerX,this.topY,J,this.leftInnerX,this.bottomY,M]}var Ma=this,B=Ma.hcLib,I=B.BLANKSTRING,Va=B.createTrendLine,n=B.pluck,U=B.getValidValue,p=B.pluckNumber,N=B.defaultPaletteOptions,va=B.getFirstValue,ib=B.getDefinedColor,$=B.parseUnsafeString,Z=B.FC_CONFIG_STRING,wa=B.extend2,ra=B.getDashStyle,jb=B.toPrecision,pa=B.stubFN,K=B.Highcharts,kb=K.Series,
W=K.hasSVG,Wa=K.hasTouch,lb=K.isIE,Na=K.extend,Fa=K.merge,Ga=K.pick,ha=K.each,Ha=K.attr,Oa=K.map,la=K.seriesTypes,xa=K.addEvent,mb=K.getPosition,nb=K.getTouchEvent,ma=K.getOptions().plotOptions,za=function(a){return a!==ya&&a!==null},Ia=document.documentMode===8,ya,Xa="rgba(192,192,192,"+(W?1.0E-6:0.0020)+")",ia=Ia?"visible":"",O="M",J="L",ea="A",M="Z",ba=Math,ca=ba.sin,da=ba.cos,ob=ba.atan2,Aa=ba.round,Ya=ba.min,ja=ba.max,Za=ba.abs,$a=ba.PI,na=ba.ceil,pb=ba.floor,ab=ba.sqrt,qa=$a/180,V=Math.PI,Ja=
V/2,oa=2*V,bb=V+Ja,qb=B.graphics.getColumnColor,Q=B.getFirstColor,Pa=B.setLineHeight,cb=B.pluckFontSize,Ba=B.getFirstAlpha,sa=B.graphics.getDarkColor,ka=B.graphics.getLightColor,aa=B.graphics.convertColor,Ca=B.COLOR_TRANSPARENT,Qa=B.POSITION_CENTER,rb=B.POSITION_TOP,Ka=B.POSITION_BOTTOM,sb=B.POSITION_RIGHT,tb=B.POSITION_LEFT,m=B.chartAPI,ub=B.titleSpaceManager,vb=B.placeLegendBlockBottom,wb=B.placeLegendBlockRight,db=B.graphics.mapSymbolName,eb=m.singleseries,y=B.COMMASTRING,fb=B.STRINGUNDEFINED,
ga=B.ZEROSTRING,Da=B.ONESTRING,fa=B.HUNDREDSTRING,Ra=B.PXSTRING,xb=B.COMMASPACE;m("column2d",{standaloneInit:!0,creditLabel:!1},m.column2dbase);m("column3d",{defaultSeriesType:"column3d",defaultPlotShadow:1,defaultZeroPlaneHighlighted:!1},m.column2d);m("bar2d",{isBar:!0,defaultSeriesType:"bar",spaceManager:m.barbase},m.column2d);m("line",{standaloneInit:!0,creditLabel:!1},m.linebase);m("area2d",{standaloneInit:!0,creditLabel:!1},m.area2dbase);m("pie2d",{standaloneInit:!0,defaultSeriesType:"pie",defaultPlotShadow:1,
sliceOnLegendClick:!0,point:function(a,d,b,c,g){var j,e,f,k=g[Z],l=k.is3d,i,h,q,E,L=0,R=0,o=[],v=p(c.plotborderthickness,l?0.1:1),s=(f=p(c.use3dlighting,1))?p(c.radius3d,c["3dradius"],90):100;i=p(c.showzeropies,1);var x=p(c.showpercentintooltip,1),u=p(c.showlabels,1),m=p(c.showvalues,1),r=p(c.showpercentvalues,c.showpercentagevalues,0),t=n(c.tooltipsepchar,c.hovercapsepchar,xb),w=n(c.labelsepchar,t),G=n(c.plotbordercolor,c.piebordercolor),F=g[Z].numberFormatter;h=b.length;var P,A,H=p(c.plotborderdashed,
0),B=p(c.plotborderdashlen,5),C=p(c.plotborderdashgap,4);s>100&&(s=100);s<0&&(s=0);if(p(c.showlegend,0))g.legend.enabled=!0,g.legend.reversed=!Boolean(p(c.reverselegend,0)),d.showInLegend=!0;for(a=0;a<h;a+=1)e=b[a],j=F.getCleanValue(e.value,!0),j===null||!i&&j===0||(o.push(e),L+=j);L===0&&(o=[]);d.enableRotation=o.length>1?p(c.enablerotation,1):0;d.is3D=l;d.use3DLighting=f;d.pieYScale=p(c.pieyscale,40);if(d.pieYScale<1)d.pieYScale=1;if(d.pieYScale>=100)d.pieYScale=80;d.pieYScale/=100;d.pieSliceDepth=
p(c.pieslicedepth,15);if(d.pieSliceDepth<1)d.pieSliceDepth=1;d.managedPieSliceDepth=d.pieSliceDepth;for(a=o.length-1;a>=0;a-=1){e=o[a];j=F.getCleanValue(e.value,!0);b=$(n(e.label,e.name,I));i=n(e.color,g.colors[a%g.colors.length]);h=n(e.alpha,c.plotfillalpha,fa);q=n(e.bordercolor,G,ka(i,l?90:25)).split(y)[0];E=c.showplotborder==ga?ga:n(e.borderalpha,c.plotborderalpha,c.pieborderalpha,"80");f={opacity:Math.max(h,E)/100};if(P=Boolean(p(e.issliced,c.issliced,0)))k.preSliced=P;A=p(e.dashed,H)?ra(n(e.dashlen,
B),n(e.dashgap,C),v):void 0;d.data.push({showInLegend:b!==I,y:j,name:b,shadow:f,toolText:$(U(e.tooltext)),color:this.getPointColor(i,h,s),_3dAlpha:h,borderColor:aa(q,E),borderWidth:v,link:U(e.link),sliced:P,dashStyle:A,doNotSlice:n(c.enableslicing,Da)!=Da});h=F.percentValue(j/L*100);q=F.dataLabels(j)||I;f=x===1?h:q;j=p(e.showlabel,u)===1?b:I;h=(i=p(e.showvalue,m))===1?r===1?h:q:I;e=U($(e.displayvalue));h=e!==void 0&&i?e:h!==I&&j!==I?j+w+h:n(j,h);b=b!=I?b+t+f:f;e=d.data[R];e.displayValue=h;e.toolText=
n(e.toolText,b);R+=1}g.legend.enabled=c.showlegend==Da?!0:!1;g.chart.startingAngle=n(o.length>1?c.startingangle:0,0);return d},getPointColor:function(a,d,b){var c,g,a=Q(a),d=Ba(d);b<100&&W?(c=Math.floor((100-0.35*b)*85)/100,c=sa(a,c),g=Math.floor((100+b)*50)/100,a=ka(a,g),d={FCcolor:{color:a+y+c,alpha:d+y+d,ratio:b+",100",radialGradient:!0}}):d={FCcolor:{color:a+y+a,alpha:d+y+d,ratio:"0,100"}};return d},configureAxis:function(a){var d=0,b=a[Z],c;a.plotOptions.series.dataLabels.style=a.xAxis.labels.style;
a.plotOptions.series.dataLabels.color=a.xAxis.labels.style.color;delete b.x;delete b[0];delete b[1];a.chart.plotBorderColor=a.chart.plotBackgroundColor=Ca;b=b.pieDATALabels=[];if(a.series.length===1&&(c=a.series[0].data)&&(d=a.series[0].data.length)>0&&a.plotOptions.series.dataLabels.enabled)for(;d--;)c[d]&&U(c[d].displayValue)!==void 0&&b.push(c[d].displayValue)},spaceManager:function(a,d,b,c){var g=a[Z],j=g.is3d,e=this.name,f=g.smartLabel,k=p(g.pieDATALabels&&g.pieDATALabels.length,0),l=0,i=d.chart,
h=p(i.managelabeloverflow,0),q=!g.preSliced&&i.enableslicing==ga&&(i.showlegend!=Da||i.interactivelegend==ga)?0:p(i.slicingdistance,20),E=p(i.pieradius,0),L=p(i.enablesmartlabels,i.enablesmartlabel,1),R=L?p(i.skipoverlaplabels,i.skipoverlaplabel,1):0,o=p(i.issmartlineslanted,1),v=p(i.labeldistance,i.nametbdistance,5),s=p(i.smartlabelclearance,5);b-=a.chart.marginRight+a.chart.marginLeft;var x=c-(a.chart.marginTop+a.chart.marginBottom),c=Math.min(x,b),u=n(i.smartlinecolor,N.plotFillColor[a.chart.paletteIndex]),
m=p(i.smartlinealpha,100),r=p(i.smartlinethickness,1),t=a.plotOptions.series.dataLabels,w=t.style,G=p(parseInt(w.lineHeight,10),12),F=a.series[0]||{},P=F.pieYScale,A=F.pieSliceDepth,c=E===0?c*0.15:E,H=0,H=2*c;t.connectorWidth=r;t.connectorColor=aa(u,m);x-=ub(a,d,b,H<x?x-H:x/2);i.showlegend==Da&&(n(i.legendposition,Ka).toLowerCase()!=sb?x-=vb(a,d,b,x/2,!0):b-=wb(a,d,b/3,x,!0));f.setStyle(w);if(k!==1)for(;k--;)d=f.getOriSize(g.pieDATALabels[k]),l=Math.max(l,d.width);L&&(v=s+q);E===0&&(j?(x-=A,H=Math.min(b/
2-l,(x/2-G)/P)-v):H=Math.min(b/2-l,x/2-G)-v,H>=c?c=H:v=Math.max(v-(c-H),q));if(j&&(k=x-2*(c*P+G),A>k))F.managedPieSliceDepth=A-k;a.plotOptions.pie3d.slicedOffset=a.plotOptions.pie.slicedOffset=q;a.plotOptions.pie3d.size=a.plotOptions.pie.size=2*c;a.plotOptions.series.dataLabels.distance=v;a.plotOptions.series.dataLabels.isSmartLineSlanted=o;a.plotOptions.series.dataLabels.enableSmartLabels=L;a.plotOptions.series.dataLabels.skipOverlapLabels=R;a.plotOptions.series.dataLabels.manageLabelOverflow=h;
if(e==="doughnut2d"||e==="doughnut3d")if(e=p(i.doughnutradius,0),k=p(i.use3dlighting,1)?p(i.radius3d,i["3dradius"],50):100,k>100&&(k=100),k<0&&(k=0),i=e===0||e>=c?c/2:e,a.plotOptions.pie3d.innerSize=a.plotOptions.pie.innerSize=2*i,k>0&&W&&(i=parseInt(i/c*100,10),e=(100-i)/2,k=parseInt(e*k/100,10),i=i+y+k+y+2*(e-k)+y+k,a.series[0]&&a.series[0].data)){h=a.series[0].data;a=0;for(k=h.length;a<k;a+=1)if(e=h[a],e.color.FCcolor)e.color.FCcolor.ratio=i}},creditLabel:!1,eiMethods:{sliceDataItem:function(a){var d=
this.jsVars.hcObj,b;if(d&&d.series&&(b=d.series[0])&&b.data&&b.data[a]&&b.data[a].slice)return b.data[b.xIncrement-1-a].slice()}}},eb);m.pie2d.eiMethods.togglePieSlice=m.pie2d.eiMethods.sliceDataItem;m("pie3d",{defaultSeriesType:"pie3d",creditLabel:!1,getPointColor:function(a){return a},defaultPlotShadow:0},m.pie2d);m("doughnut2d",{getPointColor:function(a,d,b){var c,a=Q(a),d=Ba(d);b<100&&W?(c=Math.floor((85-0.2*(100-b))*100)/100,c=sa(a,c),b=Math.floor((100-0.5*b)*100)/100,a=ka(a,b),d={FCcolor:{color:c+
y+a+y+a+y+c,alpha:d+y+d+y+d+y+d,radialGradient:!0}}):d={FCcolor:{color:a+y+a,alpha:d+y+d,ratio:"0,100"}};return d}},m.pie2d);m("doughnut3d",{defaultSeriesType:"pie3d",getPointColor:m.pie3d,defaultPlotShadow:0},m.doughnut2d);m("pareto2d",{standaloneInit:!0,point:function(a,d,b,c,g){var j,e,f,k,l,i,h,q,E,L,R,o,v,s,x,a=b.length,u=0;i={};v=g.chart.paletteIndex;var m=/3d$/.test(g.chart.defaultSeriesType),r=this.isBar,t=n(360-c.plotfillangle,90),w=p(c.plotborderthickness,1),G=g.chart.useRoundEdges,F=n(c.tooltipsepchar,
", "),P=n(c.plotbordercolor,N.plotBorderColor[v]).split(y)[0],A=c.showplotborder==ga?ga:n(c.plotborderalpha,c.plotfillalpha,fa),H=g.xAxis,B=p(c.showcumulativeline,1),C=g[Z],z=C.axisGridManager,O=C.x,J=c.showtooltip!=ga,D=[],T=[],M=p(c.use3dlighting,1),S=g[Z].numberFormatter,K=p(c.showlinevalues,c.showvalues),yb=p(c.plotborderdashed,0),X=p(c.plotborderdashlen,5),V=p(c.plotborderdashgap,4),A=m?c.showplotborder?A:ga:A,P=m?n(c.plotbordercolor,"#FFFFFF"):P;for(o=e=0;e<a;e+=1)if(R=b[e],b[e].vline)z.addVline(H,
R,o,g);else if(j=S.getCleanValue(R.value,!0),j!==null)R.value=j,D.push(R),o+=1;a=D.length;D.sort(function(a,b){return b.value-a.value});if(B)h=p(c.linedashed,0),s=Q(n(c.linecolor,N.plotBorderColor[v])),e=n(c.linealpha,100),q=p(c.linedashlen,5),E=p(c.linedashgap,4),i=p(c.linethickness,2),L={opacity:e/100},x=p(c.drawanchors,c.showanchors),x===void 0&&(x=e!=ga),f=p(c.anchorborderthickness,1),l=p(c.anchorsides,0),k=p(c.anchorradius,3),o=Q(n(c.anchorbordercolor,s)),j=Q(n(c.anchorbgcolor,N.anchorBgColor[v])),
b=Ba(n(c.anchoralpha,fa)),R=Ba(n(c.anchorbgalpha,b))*b/100,h=h?ra(q,E,i):void 0,i={yAxis:1,data:[],type:"line",color:aa(s,e),lineWidth:i,marker:{enabled:x,fillColor:aa(j,R),lineColor:aa(o,b),lineWidth:f,radius:k,symbol:db(l),startAngle:n(c.anchorstartangle,90)}};else{if(c.showsecondarylimits!=="1")c.showsecondarylimits="0";if(c.showdivlinesecondaryvalue!=="1")c.showdivlinesecondaryvalue="0"}for(e=0;e<a;e+=1)R=D[e],j=p(R.showlabel,c.showlabels,1),b=$(!j?I:va(R.label,R.name)),z.addXaxisCat(H,e,e,b),
u+=j=R.value,f=n(R.color,g.colors[e%g.colors.length])+y+(p(c.useplotgradientcolor,1)?ib(c.plotgradientcolor,N.plotGradientColor[v]):I),k=n(R.alpha,c.plotfillalpha,fa),l=n(R.ratio,c.plotfillratio),o={opacity:k/100},s=n(R.alpha,A)+I,f=qb(f,k,l,t,G,P,s,r,m),d.data.push(wa(this.getPointStub(R,j,b,g),{y:j,shadow:o,color:f[0],borderColor:f[1],borderWidth:w,use3DLighting:M,dashStyle:p(R.dashed,yb)==1?ra(X,V,w):"",tooltipConstraint:this.tooltipConstraint})),this.pointValueWatcher(g,j),B&&T.push({value:u,
dataLabel:b,tooltext:U(R.tooltext)});O.catCount=a;C[1]||(C[1]={});C[1].stacking100Percent=!0;if(B&&u>0){e=0;for(a=T.length;e<a;e+=1)R=T[e],g=d.data[e],j=R.value/u*100,v=S.percentValue(j),c=g.displayValue!==I?v:I,K==1&&(c=v),K==0&&(c=I),b=R.dataLabel,v=J?R.tooltext!==void 0?R.tooltext:(b!==I?b+F:I)+v:I,i.data.push({shadow:L,y:j,toolText:v,displayValue:c,link:g.link,dashStyle:h});return[d,i]}else return d},defaultSeriesType:"column",isDual:!0,creditLabel:!1},eb);m("pareto3d",{defaultSeriesType:"column3d",
defaultPlotShadow:1},m.pareto2d);m("mscolumn2d",{standaloneInit:!0,creditLabel:!1},m.mscolumn2dbase);m("mscolumn3d",{defaultSeriesType:"column3d",defaultPlotShadow:1,defaultZeroPlaneHighlighted:!1},m.mscolumn2d);m("msbar2d",{isBar:!0,defaultSeriesType:"bar",spaceManager:m.barbase},m.mscolumn2d);m("msbar3d",{defaultSeriesType:"bar3d",defaultPlotShadow:1,defaultZeroPlaneHighlighted:!1},m.msbar2d);m("msline",{standaloneInit:!0,creditLabel:!1},m.mslinebase);m("msarea",{standaloneInit:!0,creditLabel:!1},
m.msareabase);m("stackedcolumn2d",{isStacked:!0},m.mscolumn2d);m("stackedcolumn3d",{isStacked:!0},m.mscolumn3d);m("stackedbar2d",{isStacked:!0},m.msbar2d);m("stackedbar3d",{isStacked:!0},m.msbar3d);m("stackedarea2d",{isStacked:!0,showSum:0},m.msarea);m("marimekko",{isValueAbs:!0,distributedColumns:!0,isStacked:!0,xAxisMinMaxSetter:pa,postSeriesAddition:function(a,d){var b=a[Z],c=0,g=a.xAxis,j=100/b.marimekkoTotal,e=[],f=a.series,k=0,l=p(d.chart.plotborderthickness,1),i=a.chart.rotateValues,h=p(d.chart.rotatexaxispercentvalues,
0),l=l*-0.5-(l%2+(h?0:4)),q=h?3:0,E=i?270:0,L=wa({},a.plotOptions.series.dataLabels.style),R=parseInt(L.fontSize,10),o=b[0],v=!o.stacking100Percent,s=b.inCanvasStyle,x=this.numberFormatter,u,m,r,t,w,n,F;b.isXYPlot=!0;b.distributedColumns=!0;g.min=0;g.max=100;g.labels.enabled=!1;g.gridLineWidth=0;g.alternateGridColor=Ca;u=o.stack;d.chart.interactivelegend="0";r=0;for(o=a.xAxis.plotLines.length;r<o;r+=1)if(t=g.plotLines[r],t.isGrid)t.isCat=!0,e[t.value]=t;if(u.floatedcolumn&&(m=u.floatedcolumn[0])){u=
0;for(o=m.length;u<o;){F=m[u];c+=g=F.p||0;w=g*j;t=k+w/2;n=k+w;for(r=0;r<f.length;r+=1)a.series[r].data[u]._FCX=k,a.series[r].data[u]._FCW=w;b.showStackTotal&&a.xAxis.plotLines.push({value:t,width:0,isVline:v,isTrend:!v,zIndex:4,label:{align:Qa,textAlign:E,rotation:i?270:0,style:L,verticalAlign:rb,offsetScale:v?g<0?F.n:F.p:void 0,offsetScaleIndex:0,y:g<0?i===270?4:R:-4,x:0,text:x.yAxis(jb(g,10))}});if(e[u])e[u].value=t,e[u]._weight=w;u+=1;b.showXAxisPercentValues&&u<o&&a.xAxis.plotLines.push({value:n,
width:0,isVine:!0,label:{align:Qa,textAlign:h?tb:Qa,rotation:h?270:0,style:{color:s.color,fontSize:s.fontSize,fontFamily:s.fontFamily,lineHeight:s.lineHeight,border:"1px solid",borderColor:s.color,backgroundColor:"#ffffff",backgroundOpacity:1},verticalAlign:Ka,y:l,x:q,text:this.numberFormatter.percentValue(n)},zIndex:5});k=n}}},defaultSeriesType:"floatedcolumn"},m.stackedcolumn2d);m("msstackedcolumn2d",{series:function(a,d,b){var c,g,j,e,f=d[Z],k=0,l,i;l=[];var h;d.legend.enabled=Boolean(p(a.chart.showlegend,
1));if(a.dataset&&a.dataset.length>0){this.categoryAdder(a,d);c=0;for(g=a.dataset.length;c<g;c+=1)if(h=a.dataset[c].dataset){j=0;for(e=h.length;j<e;j+=1,k+=1)l={data:[],stack:c},i=Math.min(f.oriCatTmp.length,h[j].data&&h[j].data.length),l=this.point(b,l,h[j],a.chart,d,i,k,c),d.series.push(l)}if(this.isDual&&a.lineset&&a.lineset.length>0){j=0;for(e=a.lineset.length;j<e;j+=1,k+=1)l={data:[],yAxis:1,type:"line"},b=a.lineset[j],i=Math.min(f.oriCatTmp.length,b.data&&b.data.length),d.series.push(m.msline.point.call(this,
"msline",l,b,a.chart,d,i,k))}this.configureAxis(d,a);a.trendlines&&Va(a.trendlines,d.yAxis,d[Z],!1,this.isBar)}}},m.stackedcolumn2d);m("mscombi2d",{standaloneInit:!0,creditLabel:!1},m.mscombibase);m("mscombi3d",{series:m.mscombi2d.series,eiMethods:"view2D,view3D,resetView,rotateView,getViewAngles,fitToStage"},m.mscolumn3d);m("mscolumnline3d",{},m.mscombi3d);m("stackedcolumn2dline",{isStacked:!0,stack100percent:0},m.mscombi2d);m("stackedcolumn3dline",{isStacked:!0,stack100percent:0},m.mscombi3d);m("mscombidy2d",
{isDual:!0,secondarySeriesType:void 0},m.mscombi2d);m("mscolumn3dlinedy",{isDual:!0,secondarySeriesType:"line"},m.mscolumnline3d);m("stackedcolumn3dlinedy",{isDual:!0,secondarySeriesType:"line"},m.stackedcolumn3dline);m("msstackedcolumn2dlinedy",{isDual:!0,stack100percent:0,secondarySeriesType:"line"},m.msstackedcolumn2d);m("scrollcolumn2d",{postSeriesAddition:m.scrollbase.postSeriesAddition,tooltipConstraint:"plot",avgScrollPointWidth:40},m.mscolumn2d);m("scrollline2d",{postSeriesAddition:m.scrollbase.postSeriesAddition,
tooltipConstraint:"plot",avgScrollPointWidth:75},m.msline);m("scrollarea2d",{postSeriesAddition:m.scrollbase.postSeriesAddition,tooltipConstraint:"plot",avgScrollPointWidth:75},m.msarea);m("scrollstackedcolumn2d",{postSeriesAddition:function(a,d,b,c){m.base.postSeriesAddition.call(this,a,d,b,c);m.scrollbase.postSeriesAddition.call(this,a,d,b,c)},tooltipConstraint:"plot",avgScrollPointWidth:75},m.stackedcolumn2d);m("scrollcombi2d",{postSeriesAddition:m.scrollbase.postSeriesAddition,tooltipConstraint:"plot",
avgScrollPointWidth:40},m.mscombi2d);m("scrollcombidy2d",{postSeriesAddition:m.scrollbase.postSeriesAddition,tooltipConstraint:"plot",avgScrollPointWidth:40},m.mscombidy2d);m("scatter",{standaloneInit:!0,defaultSeriesType:"scatter",defaultZeroPlaneHighlighted:!1,creditLabel:!1},m.scatterbase);m("bubble",{standaloneInit:!0,standaloneInut:!0,defaultSeriesType:"bubble",point:function(a,d,b,c,g,j,e){if(b.data){var f,k,l,i,h,q,E,L,R,o,v=!1,s,x,a=m[a],j=b.data,u=j.length,ta=p(b.showvalues,g[Z].showValues);
l=p(c.bubblescale,1);var r=n(c.negativecolor,"FF0000"),t=g.plotOptions.bubble,w=this.numberFormatter,G=p(b.showregressionline,c.showregressionline,0);t.bubbleScale=l;d.name=U(b.seriesname);if(p(b.includeinlegend)===0||d.name===void 0)d.showInLegend=!1;l=Boolean(p(b.drawanchors,b.showanchors,c.drawanchors,1));E=n(b.plotfillalpha,b.bubblefillalpha,c.plotfillalpha,fa);L=p(b.showplotborder,c.showplotborder,1);R=Q(n(b.plotbordercolor,c.plotbordercolor,"666666"));f=n(b.plotborderthickness,c.plotborderthickness,
1);o=n(b.plotborderalpha,c.plotborderalpha,"95");L=L==1?f:0;e=n(b.color,b.plotfillcolor,c.plotfillcolor,g.colors[e%g.colors.length]);d.marker={enabled:l,fillColor:this.getPointColor(e,fa),lineColor:{FCcolor:{color:R,alpha:o}},lineWidth:L,symbol:"circle"};if(G){d.events={hide:this.hideRLine,show:this.showRLine};var F={sumX:0,sumY:0,sumXY:0,sumXsqure:0,sumYsqure:0,xValues:[],yValues:[]},P=p(b.showyonx,c.showyonx,1),A=Q(n(b.regressionlinecolor,c.regressionlinecolor,e)),H=p(b.regressionlinethickness,
c.regressionlinethickness,1);f=Ba(p(b.regressionlinealpha,c.regressionlinealpha,100));A=aa(A,f)}for(k=0;k<u;k+=1)if(i=j[k])if(f=w.getCleanValue(i.y),s=w.getCleanValue(i.x),x=w.getCleanValue(i.z,!0),f===null)d.data.push({y:null,x:s});else{v=!0;h=Q(n(i.color,i.z<0?r:e));q=n(i.alpha,E);i=a.getPointStub(i,f,s,g,b,ta);h=p(c.use3dlighting)===0?h:a.getPointColor(h,q);if(x!==null)t.zMax=t.zMax>x?t.zMax:x,t.zMin=t.zMin<x?t.zMin:x;d.data.push({y:f,x:s,z:x,displayValue:i.displayValue,toolText:i.toolText,link:i.link,
marker:{enabled:l,fillColor:h,lineColor:{FCcolor:{color:R,alpha:o}},lineWidth:L,symbol:"circle"}});this.pointValueWatcher(g,f,s,G&&F)}else d.data.push({y:null});G&&(b={type:"line",color:A,showInLegend:!1,lineWidth:H,enableMouseTracking:!1,marker:{enabled:!1},data:this.getRegressionLineSeries(F,P,u),zIndex:0},d=[d,b])}if(!v)d.showInLegend=!1;return d},postSeriesAddition:function(a,d){a.chart.hasScroll=p(d.chart.clipbubbles,1)},getPointStub:function(a,d,b,c,g,j){var c=c[Z],d=d===null?d:c.numberFormatter.dataLabels(d),
e,f=c.tooltipSepChar;c.showTooltip?U(a.tooltext)!==void 0?g=$(a.tooltext):d===null?g=!1:(c.seriesNameInToolTip&&(e=n(g&&g.seriesname)),g=e?e+f:I,g+=b?b+f:I,g+=d,g+=a.z?f+a.z:I):g=I;b=p(a.showvalue,j,c.showValues)?n(a.name,a.label)!==void 0?$(n(a.name,a.label)):d:I;a=U(a.link);return{displayValue:b,toolText:g,link:a}}},m.scatter);var Sa=function(a,d,b,c){var z;var g=a.stepZoom,j=a.options.chart.stepZoom.skipOverlapPoints,e=g.zoomHistory,f=g.currentZoomLevelIndex,k,l=g.pixelsPerPoint,i=a.series,h=i.length,
q=a.options._FCconf,E=g.maxIndex,L={},p,o,v,s,x,u;x=q.numVisibleLabels;var m=q.visibleLabelDistance,r,q=!1;if(c<f)q=!0,f=g.currentZoomLevelIndex=c||0,e.splice(f+1,e.length),e=e[f],l=e.stepping,o=e.seriesStart,c=e.perPointPixelDistance,s=e.scrollRatio,p=g.scrollPosition=e.scrollPosition,d=e._startIndex,b=e._stopIndex,g.scrollablePXLength=e.scrollablePXLength;else{d>b&&(r=d,d=b,b=r);p=a.plotWidth;o=b-d;c=p/o;r=x?na((b-d)/x):c<m?Math.ceil(m/c):1;l=c<l?Math.ceil(l/c):1;c=p/(o-o%l);o=d%l;v=E-E%l;k=(v-
o)*c;s=p/k;u=k-p;p=u>0?(d-o)*c/(k-p):0;g.scrollPosition=p;g.scrollablePXLength=u;if((k=e[f])&&k.stepping===l&&k.seriesStart===o&&k.seriesEnd===v&&k.perPointPixelDistance===c)return;e[g.currentZoomLevelIndex=f+=1]={seriesStart:o,seriesEnd:v,stepping:l,perPointPixelDistance:c,visiblePointDistance:l*c,seriesConf:[],scrollRatio:s,scrollPosition:p,scrollablePXLength:u,_startIndex:d,_stopIndex:b}}var t,e=[],w,n,F,P;v=g.catLabelArr;var A,H;x?r=b!==void 0&&d!==void 0?na((b-d)/x):na(E/x):r===void 0&&(r=c<
m?na(m/c):1);for(m=0;m<=E;m+=1){k=m-o;x=k*c;u=k<0||k%l!==0;t=k<0||k%r!==0;k={x:x,visibility:u?"hidden":ia};if(v&&(P=v[m]))P.attr({x:x+g.xDisplacement,visibility:t?"hidden":ia});for(t=h;t--;)if(w=i[t],F=w.data[m],F.plotX=x,z=e[t]||(e[t]={path:[],addMove:!0,addLine:!1,lastMovePoint:[],connectNullData:w.options.connectNullData}),w=z,n=w.path,(A=F.graphic)&&A.attr(k),(H=F.dataLabel)&&H.attr(k),!j||!u)if(za(F&&F.plotY)){if(w.addLine)n.push(O,w.lastMovePoint[0],w.lastMovePoint[1],J),w.addLine=!1;w.addMove?
(w.addLine=!0,w.addMove=!1,w.lastMovePoint[0]=x,w.lastMovePoint[1]=F.plotY):n.push(x,F.plotY)}else if(!w.connectNullData)w.addMove=!0,w.addLine=!1}for(t=0;t<h;t+=1)w=e[t]||(e[t]={path:[O],isLastMoveComand:!0}),n=w.path,i[t].graphLine.attr({d:n}),i[t].graphPath=n;g.scroller.setScrollRatio(s);g.scroller.setScrollPosition(p);f||(d=f=0,b=v&&v.length-1||0);L.reset=f===0;L.level=f;L.startIndex=d;L.startLabel=v&&v[d].textStr;L.endIndex=b;L.endLabel=v&&v[b].textStr;L.action=q?"out":"in";B.raiseEvent("zoomed",
L,a.options.instanceAPI.chartInstance,[a.options.instanceAPI.chartInstance.id,L.startIndex,L.stopIndex,L.startLabel,L.stopLabel,L.action,L.level]);Ma.raiseEvent(q?"zoomedout":"zoomedin",L,a.options.instanceAPI.chartInstance)},zb=function(a,d){var b=d.zoomHistory[d.currentZoomLevelIndex],c=b.perPointPixelDistance,g=a.selectionWidth,j=d.maxIndex,b=b.scrollablePXLength*b.scrollPosition+a.selectionLeft,g=b+g,b=pb(b/c),g=na(g/c);g>j&&(g=j);return{max:g,min:b}},Ab=function(a,d,b){var c=this.tracker.normalizeMouseEvent,
g=this.options.chart.stepZoom,j=this.renderer,e=this.plotLeft,f=this.plotTop,k=this.plotWidth,l=this.plotHeight,i=g.pinPaneBorderThickness,h=j.clipRect(e+a,f,d,l),q,E,p=[],m=0;q=j.g("group").attr({x:0,y:0,zIndex:2}).clip(h).add();E=j.rect(e+a,f-i/2,d,l+i,0).attr({stroke:g.pinPaneBorderColor,fill:g.pinPaneBgColor,strokeWidth:i,isOverlay:!0}).css({cursor:"w-resize"}).add(q);ha(this.series,function(a){var b=a.options,c=b.color,b=ja(b.lineWidth+g.pinLineThicknessDelta,1),c=j.path(a.graphPath).attr({stroke:c,
"stroke-width":b,"stroke-linecap":"round",dashstyle:lb&&!W?ra(b+1,b,b):ra(b,b+1,b),visibility:a.visible?ia:"hidden"});p.push(c);c.translate(a.group.attr("translateX"),f).add(q)});xa(E.element,"dragstart drag",function(b){var e=b.type,b=c(nb(b));e==="dragstart"?m=b.pageX-(q.attr("translateX")||0):(b=b.pageX-m,e=b+a,e<0?b=-a:e+d>k&&(b=k-d-a),q.translate(b))});B.raiseEvent("pinned",{startIndex:b.min,endIndex:b.max,startLabel:this.stepZoom.catLabelArr[b.min].textStr,endLabel:this.stepZoom.catLabelArr[b.max].textStr},
this.options.instanceAPI.chartInstance,[this.options.instanceAPI.chartInstance.id,b.min,b.max,this.stepZoom.catLabelArr[b.min].textStr,this.stepZoom.catLabelArr[b.max].textStr]);return{destroy:function(){ha(p,function(a){a.destroy()});E.destroy();q.destroy()}}},Bb=function(a){var d=this,b=d.stepZoom,c=d.options.chart.stepZoom,g=a.selectionLeft,j=zb(a,b);if(b.pinActive)b.pinComposite&&b.pinComposite.destroy(),b.pinComposite=Ab.call(d,g,a.selectionWidth,j,b);else{j.max>j.min&&Sa(d,j.min,j.max);a=b.currentZoomLevelIndex;
if(!b.zoButton)b.zoButton=d.addButton({onclick:function(){var a=b.currentZoomLevelIndex-1;Sa(d,void 0,void 0,a);b.pinButton&&b.pinActive&&b.pinButton.onClick();a<=1&&b.resetButton.hide();b.currentZoomLevelIndex==0&&b.zoButton.hide()},tooltip:c.showToolBarButtonTooltext&&c.btnZoomOutTooltext,symbol:"zoomOutIcon"});b.zoButton[a===0?"hide":"show"]();if(!b.resetButton)b.resetButton=d.addButton({onclick:function(){Sa(d,void 0,void 0,0);b.resetButton&&b.resetButton.hide();b.zoButton&&b.zoButton.hide();
b.pinButton&&b.pinActive&&b.pinButton.onClick();B.raiseEvent("resetzoomchart",{},d.options.instanceAPI.chartInstance,[d.options.instanceAPI.chartInstance.id])},tooltip:c.showToolBarButtonTooltext&&c.btnResetChartTooltext,symbol:"resetIcon",symbolFill:"none",hoverSymbolFill:"none"});b.resetButton[d.stepZoom.currentZoomLevelIndex>1?"show":"hide"]()}};Na(B.eventList,{zoomed:"FC_Zoomed",pinned:"FC_Pinned",resetzoomchart:"FC_ResetZoomChart"});m("zoomline",{standaloneInit:!0,hasVDivLine:!0,defaultSeriesType:"stepzoom",
canvasborderthickness:1,tooltipConstraint:"plot",chart:function(){var a=this.dataObj.chart,d,b;U(this.dataObj.chart.axis,I).toLowerCase()=="log"&&wa(this,m.logbase);b=this.base.chart.apply(this,arguments);d=b.chart.stepZoom;!U(a.caption)&&!U(a.subcaption)&&(b.chart.marginTop+=15);b.chart.animation=!1;(b.plotOptions||(b.plotOptions={}))&&(b.plotOptions.series||(b.plotOptions.series={}));b.plotOptions.series.animation=!1;b.chart.nativeZoom=!1;b.chart.events.selection=Bb;if(!b.callbacks)b.callbacks=
[];b.callbacks.push(function(){var a=this,b=a.renderer,j=a.stepZoom,e=j.pinButton;if(!e&&a.options.chart.stepZoom.allowPinMode)e=j.pinButton=a.addButton({onclick:function(){if(j.pinActive=!j.pinActive)e.tooltipOptions.point.toolText=d.showToolBarButtonTooltext&&"Switch to Zoom Mode";else{if(j.pinComposite)j.pinComposite=j.pinComposite.destroy();e.tooltipOptions.point.toolText=d.showToolBarButtonTooltext&&d.btnSwitchToPinModeTooltext}e.activate(j.pinActive);Ma.raiseEvent("pinmodestatechange",{state:j.pinActive},
a.options.instanceAPI.chartInstance)},tooltip:d.showToolBarButtonTooltext&&d.btnSwitchToPinModeTooltext,symbol:"pinModeIcon"});if(!b.forExport)b.batchCapacity=50,b.batchSpeed=1,b.simpleAppend=!0,b.processBatch()});return b},xAxisMinMaxSetter:function(){this.base.xAxisMinMaxSetter.apply(this,arguments);var a=this.hcJSON,d=a.xAxis,a=a[Z].x;d.min=0;d.max=a.catCount-1},series:function(a,d,b){var c,g,j=d[Z],e;c=a.chart;d.legend.enabled=Boolean(p(c.showlegend,1));d.chart.valuePosition=n(c.valueposition,
"auto").toLowerCase();if(a.dataset&&a.dataset.length>0&&a.categories&&a.categories[0]&&a.categories[0].category){this.categoryAdder(a,d);c=0;for(g=a.dataset.length;c<g;c+=1)e={data:[]},d.series.push(this.point(b,e,a.dataset[c],a.chart,d,j.oriCatTmp.length,c)),e=!0;e&&(this.configureAxis(d,a),a.trendlines&&!this.isLog&&Va(a.trendlines,d.yAxis,j,!1,this.isBar))}},point:function(a,d,b,c,g,j,e){var f,k,l,i,h,q,E,L,m,o,v,s,x,u,ta,r,t,w=b.data,G=g[Z],a=n(d.type,this.defaultSeriesType),F=g.plotOptions[a]&&
g.plotOptions[a].stacking,P=n(this.isValueAbs,G.isValueAbs,!1),G=p(d.yAxis,0),A=this.numberFormatter;t=p(c.showshadow,1);ta=p(c.compactdatamode,0);r=n(c.dataseparator,"|");f=n(b.seriesname,I);k=Q(n(b.color,c.linecolor,g.colors[e%g.colors.length]));l=n(b.alpha,c.linealpha,fa);i=p(b.linethickness,c.linethickness,2);h=Boolean(p(b.dashed,c.linedashed,0));q=p(b.linedashlen,c.linedashlen,5);E=p(b.linedashgap,c.linedashgap,4);e=p(b.showvalues,c.showvalues);L=p(b.drawanchors,b.showanchors,c.drawanchors,c.showanchors);
m=p(b.anchorsides,c.anchorsides,0);o=p(b.anchorradius,c.anchorradius,3);v=Q(n(b.anchorbordercolor,c.anchorbordercolor,k));s=p(b.anchorborderthickness,c.anchorborderthickness,1);x=Q(n(b.anchorbgcolor,c.anchorbgcolor,k));u=n(b.anchoralpha,c.anchoralpha,fa);c=n(b.anchorbgalpha,c.anchorbgalpha,u);d.marker={enabled:L===void 0?l!=0:!!L,fillColor:{FCcolor:{color:x,alpha:c*u/100+I}},lineColor:{FCcolor:{color:v,alpha:u+I}},lineWidth:s,radius:o,symbol:db(m)};d.name=f;d.color={FCcolor:{color:k,alpha:l}};d.shadow=
{opacity:t?l/100:0};d.lineWidth=i;d.dashStyle=h?ra(q,E,i):void 0;if(p(b.includeinlegend)===0||d.name===void 0||l==0&&L!==1)d.showInLegend=!1;if(w)if(ta){w=w.split(r);for(b=0;b<j;b+=1)c=A.getCleanValue(w[b]),c===null?d.data.push({y:null}):(f=A.dataLabels(c),t=e?f:I,d.data.push({y:c,displayValue:t,toolText:f}),this.pointValueWatcher(g,c,G,F,b,0,a))}else for(b=0;b<j;b+=1)(f=w[b])?(c=A.getCleanValue(f.value,P),c===null?d.data.push({y:null}):(ta=Q(n(f.color,k)),r=n(f.alpha,l),f=U($(f.tooltext),A.dataLabels(c)),
t=e?f:I,d.data.push({displayValue:t,toolText:f,y:c,color:{FCcolor:{color:ta,alpha:r}}}),this.pointValueWatcher(g,c,G,F,b,0,a))):d.data.push({y:null});return d},categoryAdder:function(a,d){var b,c=0,g,j=d[Z],e=d.xAxis,f,k=j.x,l=a.chart,i=d.chart,h=p(l.showlabels,1);g=p(l.pixelsperpoint,15);i.zoomType="x";e.maxZoom=2;g<=0&&(g=15);j.pixelsperpoint=g;if(a.categories&&a.categories[0]&&a.categories[0].category){if(a.categories[0].font)d.xAxis.labels.style.fontFamily=a.categories[0].font;if((g=p(a.categories[0].fontsize))!==
void 0)g<1&&(g=1),d.xAxis.labels.style.fontSize=g+Ra,Pa(d.xAxis.labels.style);if(a.categories[0].fontcolor)d.xAxis.labels.style.color=a.categories[0].fontcolor.split(y)[0].replace(/^\#?/,"#");g=d[Z].oriCatTmp;var q=a.categories[0].category;b=p(l.compactdatamode,0);f=n(l.dataseparator,"|");if(b){q=q.split(f);for(b=0;b<q.length;b+=1)f=$(va(q[b],q[b].name)),g[c]=f,c+=1}else for(b=0;b<q.length;b+=1)q[b].vline||(f=q[b].showlabel==="0"?I:$(va(a.categories[0].category[b].label,a.categories[0].category[b].name)),
g[c]=va($(a.categories[0].category[b].tooltext),f),c+=1);if(h)e.categories=g}e=c-1||1;j.displayStartIndex=p(l.displaystartindex,1)-1;j.displayEndIndex=p(l.displayendindex,c||2)-1;if(j.displayStartIndex<0||j.displayStartIndex>=e)j.displayStartIndex=0;if(j.displayEndIndex<=j.displayStartIndex||j.displayEndIndex>e)j.displayEndIndex=e;k.catCount=c;i.hasScroll=!0;c=i.stepZoom={};c.pixelsperpoint=j.pixelsperpoint;c.displayStartIndex=j.displayStartIndex;c.displayEndIndex=j.displayEndIndex;c.scrollColor=
Q(n(l.scrollcolor,N.altHGridColor[d.chart.paletteIndex]));c.scrollHeight=p(l.scrollheight,16);c.scrollPadding=p(l.scrollpadding,d.chart.plotBorderWidth);c.scrollBtnWidth=p(l.scrollbtnwidth,l.scrollheight,16);c.scrollBtnPadding=p(l.scrollbtnpadding,0);j.marginBottomExtraSpace+=c.scrollPadding+c.scrollHeight},postSeriesAddition:function(a,d){var b=d.chart,c=a.chart.stepZoom,g=N.canvasBorderColor[this.paletteIndex];if(c)c.allowPinMode=p(b.allowpinmode,1),c.skipOverlapPoints=!!p(b.skipoverlappoints,1),
c.showToolBarButtonTooltext=p(b.showtoolbarbuttontooltext,1),c.btnResetChartTooltext=n(b.btnresetcharttooltext,"Reset Zoom"),c.btnZoomOutTooltext=n(b.btnzoomouttooltext,"Zoom out one level"),c.btnSwitchToZoomModeTooltext=n(b.btnswitchtozoommodetooltext,"Select a subset of data to zoom into it for detailed view"),c.btnSwitchToPinModeTooltext=n(b.btnswitchtopinmodetooltext,"Switch to Pin Mode"),c.pinLineThicknessDelta=p(b.pinlinethicknessdelta,0),c.pinPaneBorderThickness=p(b.pinpaneborderthickness,
1),c.pinPaneBorderColor=aa(n(b.pinpanebordercolor,g),p(b.pinpaneborderalpha,15)),c.pinPaneBgColor=aa(n(b.pinpanebgcolor,g),p(b.pinpanebgalpha,15))},placeHorizontalAxis:function(a,d,b,c,g,j,e){var f=b[Z],k,l,i,h,q,E,L,m,o=0,v=0,s=10,x=1,u=0,n=0,r=!1,t=!1,w=!1,G=p(c.chart.labelstep,0);m=p(c.chart.numvisiblelabels,0);var F=d.labelDisplay,P=d.rotateLabels,A=d.horizontalLabelPadding,H=f.marginBottomExtraSpace,B=b.chart.marginLeft,C=b.chart.marginRight,z=f.smartLabel,y=d.slantLabels,O=g/(a.max-a.min),D=
0,T=0,n={w:0,h:0};if(a.labels.style)q=a.labels.style,z.setStyle(q),l=z.getOriSize("W"),s=l.height,E=l.width+4,L=z.getOriSize("WWW").width+4;var J,S,M=[],K=[];l=l=0;var X,V,Q=d.horizontalAxisNamePadding;S=0;var d=d.staggerLines,N=D;if(a.title&&a.title.text!=I)q=a.title.style,z.setStyle(q),u=z.getOriSize("W").height,a.title.rotation=0,l=z.getSmartText(a.title.text,g,j),v=l.height;b.chart.marginLeft!=parseInt(c.chart.chartleftmargin,10)&&(i=!0);b.chart.marginRight!=parseInt(c.chart.chartrightmargin,
10)&&(k=!0);S=g-e;switch(F){case "none":r=w=!0;P&&(o=y?300:270,l=s,s=E,E=l,r=!0);break;case "rotate":o=y?300:270;l=s;s=E;E=l;r=!0;break;case "stagger":t=r=!0;c=Math.floor((j-u)/s);c<d&&(d=c);break;default:P&&(o=y?300:270,l=s,s=E,E=l)}P=0;e=a.plotLines;for(c=e.length;P<c;P+=1)(l=e[P])&&l.label&&typeof l.label.text!==fb&&K.push(l);e=a.plotBands;P=0;for(c=e.length;P<c;P+=1)(l=e[P])&&l.label&&typeof l.label.text!==fb&&K.push(l);e=a.categories||[];P=0;for(c=e.length;P<c;P+=1)M.push({value:P,label:{text:e[P]}});
P=M.length-1;c=M.length;t&&(d>c?d=c:d<2&&(d=2));if(c){a.scroll&&a.scroll.viewPortMin&&a.scroll.viewPortMax?(J=a.scroll.viewPortMin,l=a.scroll.viewPortMax,k=i=!1):(J=a.min,l=a.max);X=f.width*0.08;V=(M[0].value-J)*O;J=(l-M[P].value)*O;f.maxLabelWidth=X;f.visibleLabelDistance=f.width*0.1;f.numVisibleLabels=m;if(F==="auto"){if(X>O&&X<L)y?o=300:(o=270,f.visibleLabelDistance=f.width*0.07,f.maxLabelWidth=s),l=s,s=E,E=l,r=!0}else if(F==="rotate"){if(!y)f.visibleLabelDistance=f.width*0.07,f.maxLabelWidth=
s}else F==="stagger"&&(X*=d);L=(V+B)*2;if(m=e[0])a.labels.style&&z.setStyle(a.labels.style),m=Math.min(X,z.getOriSize(m).width+4),i&&m>L&&(l=(m-L)/2,g-=l,S-=l,b.chart.marginLeft+=l);L=(J+C)*2;if(m=e[P])a.labels.style&&z.setStyle(a.labels.style),m=Math.min(X,z.getOriSize(h).width+4),k&&m>L&&(l=(m-L)/2,g-=l,S-=l,b.chart.marginRight+=l);w||(G?(X*=G,X=Math.max(X,E)):(x=Math.max(1,Math.ceil(E/X)),X*=x));for(i=0;i<c;i+=1)if(l=M[i],i%x&&l.label)l.label.text=I;else if(l&&l.label&&U(l.label.text)!==void 0){h=
l.label;if(h.style&&h.style!==q)q=h.style,z.setStyle(q);if(o&&w)k=z.getOriSize(h.text),n.w=ja(n.w,k.width+4),n.h=ja(n.h,k.height);else if(!w)k=o||t?z.getOriSize(h.text):z.getSmartText(h.text,X-4,j,r),n.w=Math.max(n.w,k.width+4),n.h=Math.max(n.h,k.height)}}i=0;for(c=K.length;i<c;i+=1)if((l=K[i])&&l.label&&U(l.label.text)!==void 0){h=l.label;if(h.style&&h.style!==q)q=h.style,z.setStyle(q);k=z.getOriSize(h.text);h.verticalAlign===Ka?D=ja(D,k.height):T=ja(T,k.height)}a.scroll&&a.scroll.enabled&&!o&&!w&&
(h=n.w/2,b.chart.marginLeft<h&&(i=h-b.chart.marginLeft,S>i&&(g-=i,S-=i,b.chart.marginLeft+=i)),b.chart.marginRight<h&&(i=h-b.chart.marginRight,S>i&&(g-=i,b.chart.marginRight+=i)));if(w){if(S=s,o)S=n.w}else S=o?n.w:t?d*s:n.h;S>0&&(N+=A+S);v>0&&(N+=v+Q);h=T+N+2;h>j&&(h-=j,Q>h?(Q-=h,h=0):(h-=Q,Q=0,A>h?(A-=h,h=0):(h-=A,A=0)),T>h?T-=h:(T>0&&(h-=T,T=0),h>0&&(D>h?D-=h:(D>0&&(h-=D,D=0),h>0&&((l=v-u)>h?v-=h:(h-=l,v=u,h>0&&((l=S-s)>h?S-=h:(h-=l,S=s,h>0&&(h-=v+Q,v=0,h>0&&(h-=S,S=0,h>0&&(A-=h)))))))))));A+=H;
u=S+A;j=f.is3d?-b.chart.xDepth:0;c=M.length;n=0;o?(s=X,X=S-4,a.labels.rotation=o,a.labels.align="right",a.labels.y=A-H+4,a.labels.x=E/2):t?X=X*d-4:(s=S,X-=4);for(i=0;i<c;i+=x)if((l=M[i])&&l.label&&U(l.label.text)!==void 0){h=l.label;if(h.style&&h.style!==q)q=h.style,z.setStyle(q);if(!w)k=z.getSmartText(h.text,X,s,r),a.categories[i]=k.text;n+=1}c=K.length;for(i=o=E=0;i<c;i+=1)if((l=K[i].plotObj?K[i].plotObj:K[i])&&l.label&&U(l.label.text)!==void 0){h=l.label;if(h.style&&h.style!==q)q=h.style,z.setStyle(q);
h.verticalAlign===Ka?(k=z.getSmartText(h.text,g,D,!0),o=Math.max(o,k.height),h.text=k.text,h.y=u+z.getOriSize("W").height,h.x=j):(k=z.getSmartText(h.text,g,T,!0),E=Math.max(E,k.height),h.text=k.text,h.y=-(T-z.getOriSize("W").height+A+2))}if(v>0)z.setStyle(a.title.style),l=z.getSmartText(a.title.text,g,v),a.title.text=l.text,a.title.margin=u+o+Q;N=o;if(S>0)f.horizontalAxisHeight=A+S-H,N+=f.horizontalAxisHeight;v>0&&(N+=v+Q);b.chart.marginBottom+=N;E>0&&(b.chart.marginTop+=E,N+=E);return N},creditLabel:!1,
defaultPlotShadow:1},m.msline);m("ssgrid",{standaloneInit:!0,defaultSeriesType:"ssgrid",chart:function(){var a=this.containerElement,d=this.dataObj,b=this.chartInstance,d=wa({},d);d.chart=d.chart||d.graph||{};delete d.graph;var c,g,j,e=0,f,k,l=[],i=d.chart,h=d.data,q=h&&h.length,d=this.smartLabel,E=this.numberFormatter,m=a.offsetHeight,R=a.offsetWidth,o={},v=e=0,e=(i.palette>0&&i.palette<6?i.palette:p(this.paletteIndex,1))-1,a={chart:{renderTo:a,ignoreHiddenSeries:!1,events:{},spacingTop:0,spacingRight:0,
spacingBottom:0,spacingLeft:0,marginTop:0,marginRight:0,marginBottom:0,marginLeft:0,borderRadius:0,borderColor:"#000000",borderWidth:1,defaultSeriesType:"ssgrid",style:{fontFamily:n(i.basefont,"Verdana"),fontSize:cb(i.basefontsize,20)+Ra,color:n(i.basefontcolor,N.baseFontColor[e]).replace(/^#?([a-f0-9]+)/ig,"#$1")},plotBackgroundColor:Ca},labels:{smartLabel:d},colors:["AFD8F8","F6BD0F","8BBA00","FF8E46","008E8E","D64646","8E468E","588526","B3AA00","008ED6","9D080D","A186BE","CC6600","FDC689","ABA000",
"F26D7D","FFF200","0054A6","F7941C","CC3300","006600","663300","6DCFF6"],credits:{href:"http://www.fusioncharts.com?BS=FCHSEvalMark",text:"FusionCharts",enabled:this.creditLabel},legend:{enabled:!1},series:[],subtitle:{text:I},title:{text:I},tooltip:{enabled:!1},exporting:{buttons:{exportButton:{},printButton:{enabled:!1}}}},s=a.colors,x=a.colors.length,u=0,y=f=g=0,v=c=k=0;g=b.jsVars.cfgStore;b=a.chart;Pa(a.chart.style);o.showPercentValues=p(g.showpercentvalues,i.showpercentvalues,0);o.numberItemsPerPage=
n(g.numberitemsperpage,i.numberitemsperpage);o.showShadow=p(g.showshadow,i.showshadow,0);o.baseFont=n(g.basefont,i.basefont,"Verdana");j=cb(g.basefontsize,i.basefontsize,10);o.baseFontSize=j+Ra;o.baseFontColor=Q(n(g.basefontcolor,i.basefontcolor,N.baseFontColor[e]));o.alternateRowBgColor=Q(n(g.alternaterowbgcolor,i.alternaterowbgcolor,N.altHGridColor[e]));o.alternateRowBgAlpha=n(g.alternaterowbgalpha,i.alternaterowbgalpha,N.altHGridAlpha[e])+I;o.listRowDividerThickness=p(g.listrowdividerthickness,
i.listrowdividerthickness,1);o.listRowDividerColor=Q(n(g.listrowdividercolor,i.listrowdividercolor,N.borderColor[e]));o.listRowDividerAlpha=p(g.listrowdivideralpha,i.listrowdivideralpha,N.altHGridAlpha[e])+15+I;o.colorBoxWidth=p(g.colorboxwidth,i.colorboxwidth,8);o.colorBoxHeight=p(g.colorboxheight,i.colorboxheight,8);o.navButtonRadius=p(g.navbuttonradius,i.navbuttonradius,7);o.navButtonColor=Q(n(g.navbuttoncolor,i.navbuttoncolor,N.canvasBorderColor[e]));o.navButtonHoverColor=Q(n(g.navbuttonhovercolor,
i.navbuttonhovercolor,N.altHGridColor[e]));o.textVerticalPadding=p(g.textverticalpadding,i.textverticalpadding,3);o.navButtonPadding=p(g.navbuttonpadding,i.navbuttonpadding,5);o.colorBoxPadding=p(g.colorboxpadding,i.colorboxpadding,10);o.valueColumnPadding=p(g.valuecolumnpadding,i.valuecolumnpadding,10);o.nameColumnPadding=p(g.namecolumnpadding,i.namecolumnpadding,5);o.borderThickness=p(g.borderthickness,i.borderthickness,1);o.borderColor=Q(n(g.bordercolor,i.bordercolor,N.borderColor[e]));o.borderAlpha=
n(g.borderalpha,i.borderalpha,N.borderAlpha[e])+I;o.bgColor=n(g.bgcolor,i.bgcolor,"FFFFFF");o.bgAlpha=n(g.bgalpha,i.bgalpha,fa);o.bgRatio=n(g.bgratio,i.bgratio,fa);o.bgAngle=n(g.bgangle,i.bgangle,ga);b.borderRadius=o.borderThickness/16;b.borderWidth=o.borderThickness;b.borderColor={FCcolor:{color:o.borderColor,alpha:o.borderAlpha}};b.backgroundColor={FCcolor:{color:o.bgColor,alpha:o.bgAlpha,ratio:o.bgRatio,angle:o.bgAngle}};b.borderRadius=p(i.borderradius,0);j={fontFamily:o.baseFont,fontSize:o.baseFontSize,
color:o.baseFontColor};Pa(j);d.setStyle(j);for(e=0;e<q;e+=1)if(c=h[e],f=E.getCleanValue(c.value),k=$(va(c.label,c.name)),g=Q(n(c.color,s[e%x])),n(c.alpha,i.plotfillalpha,fa),k!=I||f!=null)l.push({value:f,label:k,color:g}),u+=f,v+=1;for(e=0;e<v;e+=1)c=l[e],f=c.value,c.dataLabel=c.label,c.displayValue=o.showPercentValues?E.percentValue(f/u*100):E.dataLabels(f),h=d.getOriSize(c.displayValue),y=Math.max(y,h.width+o.valueColumnPadding);o.numberItemsPerPage?o.numberItemsPerPage>=v?(o.numberItemsPerPage=
v,f=m/o.numberItemsPerPage,g=v):(E=m,E-=2*(o.navButtonPadding+o.navButtonRadius),g=o.numberItemsPerPage,f=E/g):(e=parseInt(j.lineHeight,10),e+=2*o.textVerticalPadding,e=Math.max(e,o.colorBoxHeight),m/e>=v?(f=m/v,g=v):(E=m,E-=2*(o.navButtonPadding+o.navButtonRadius),g=Math.floor(E/e),f=E/g));k=R-o.colorBoxPadding-o.colorBoxWidth-o.nameColumnPadding-y-o.valueColumnPadding;c=o.colorBoxPadding+o.colorBoxWidth+o.nameColumnPadding;b.height=m;b.width=R;b.rowHeight=f;b.labelX=c;b.colorBoxWidth=o.colorBoxWidth;
b.colorBoxHeight=o.colorBoxHeight;b.colorBoxX=o.colorBoxPadding;b.valueX=o.colorBoxPadding+o.colorBoxWidth+o.nameColumnPadding+k+o.valueColumnPadding;b.valueColumnPadding=o.valueColumnPadding;b.textStyle=j;b.listRowDividerAttr={"stroke-width":o.listRowDividerThickness,stroke:{FCcolor:{color:o.listRowDividerColor,alpha:o.listRowDividerAlpha}}};b.alternateRowColor={FCcolor:{color:o.alternateRowBgColor,alpha:o.alternateRowBgAlpha}};b.navButtonRadius=o.navButtonRadius;b.navButtonPadding=o.navButtonPadding;
b.navButtonColor=o.navButtonColor;b.navButtonHoverColor=o.navButtonHoverColor;b.lineHeight=parseInt(j.lineHeight,10);m=[];o=0;E=!0;for(e=0;e<v&g!=0;e+=1)e%g==0&&(m.push({data:[],visible:E}),E=!1,o+=1),c=l[e],m[o-1].data.push({label:d.getSmartText(c.dataLabel,k,f).text,displayValue:c.displayValue,y:c.value,color:c.color});a.series=m;a.exporting.enabled=i.exportenabled=="1"?!0:!1;a.exporting.buttons.exportButton.enabled=i.exportshowmenuitem=="0"?!1:!0;a.exporting.filename=i.exportfilename?i.exportfilename:
"FusionCharts";a.exporting.width=R;return a},creditLabel:!1},m.base);ma.ssgrid=Fa(ma.pie,{states:{hover:{}}});var hb=function(a,d){var b=a.currentSeriesIndex,c=a.series,g=d?b-1:b+1;if(c[g])c[b].hide(),c[g].show(),a.currentSeriesIndex=g,gb(a)},gb=function(a){var d=a.series.length,b=a.currentSeriesIndex,c=a.naviigator;c.translate(0,a.series[b].data.length*a.options.chart.rowHeight);b===0?c.navElePrv.hide():c.navElePrv.show();b===d-1?c.navEleNxt.hide():c.navEleNxt.show()},Cb=function(a){var d=a.renderer,
b=a.options.chart,c=b.navButtonRadius,g=c*0.67,j=b.navButtonPadding+g,e=b.width-20,f=b.navButtonHoverColor,k=b.navButtonColor,l,i;if(a.series.length>1){var h=a.naviigator=d.g("navigator").attr({zIndex:4}).add();h.navElePrv=b=d.g("navElePrv").add(h);l=d.path([O,20,j,J,20+c+g,j-g,20+c,j,20+c+g,j+g,"Z"]).attr({fill:k}).add(b);d.circle(20+c,j,c).attr({fill:Ca,cursor:"pointer"}).on("mouseover",function(){l.attr({fill:f,cursor:"pointer"})}).on("mouseout",function(){l.attr({fill:k})}).on("click",function(){hb(a,
!0)}).add(b);h.navEleNxt=b=d.g("navEleNxt").add(h);i=d.path([O,e,j,J,e-c-g,j-g,e-c,j,e-c-g,j+g,"Z"]).attr({fill:k,cursor:"pointer"}).add(b);d.circle(e-c,j,c).attr({fill:Ca,cursor:"pointer"}).on("mouseover",function(){i.attr({fill:f})}).on("mouseout",function(){i.attr({fill:k})}).on("click",function(){hb(a)}).attr({fill:k}).add(b)}},pa=K.extendClass(la.pie,{type:"ssgrid",translate:function(){var a=this.chart.options.chart,d=0,b=a.width,c=a.rowHeight,g=a.colorBoxWidth,j=a.colorBoxHeight,e=a.colorBoxX,
f=a.labelX,k=a.valueX;ha(this.data,function(a){a.shapeType="rect";a.alternateGradientBox={x:0,y:d,width:b,height:c,r:0};a.rowDivider=[O,0,d,J,b,d];a.colorBoxArgs={x:e,y:d+c/2-j/2,width:g,height:j,r:0};a.labelX=f;a.valueX=k;d+=c});this.options.lastRowDivider=[O,0,d,J,b,d]},drawPoints:function(){var a=this.chart.options.chart,d=this.chart.renderer,b,c=this.group,g=a.alternateRowColor,j=a.listRowDividerAttr,e=this.options.lastRowDivider,f=a.rowHeight,k=a.textStyle,l=a.lineHeight,i=a.width,h=a.valueColumnPadding,
q,m,p,n,o,v,s;ha(this.data,function(a,e){b=a.graphic;q=a.rowDivider;m=a.colorBoxArgs;p=a.alternateGradientBox;v=a.valueX;if(!b)a.graphic=d.path(q).attr(j).add(c),e%2==0&&d.rect(p).attr({fill:g,"stroke-width":0}).add(c),a.symbol=d.rect(m).attr({fill:a.color,"stroke-width":0,stroke:"#000000"}).add(c),n=d.text(a.label,a.labelX).css(k).add(c),o=q[2]+f/2+l-n.getBBox().height/2,n.attr({y:o}),n=d.text(a.displayValue,v).css(k).add(c),s=n.getBBox(),o=q[2]+f/2+l-s.height/2,n.attr({y:o,x:v+(i-v-h-s.width)})});
d.path(e).attr(j).add(c)},render:function(){var c;var a,d=this.chart;a=d.renderer;var b=this.options;d.naviigator||Cb(d);if(!this.group)c=this.group=a.g("series"),a=c,a.attr({visibility:this.visible?ia:"hidden",zIndex:b.zIndex}).translate(d.plotLeft,d.plotTop).add(d.seriesGroup);this.drawPoints();this.drawDataLabels();if(this.visible)d.currentSeriesIndex=this.index,d.naviigator&&gb(d);this.options.animation&&this.animate&&this.animate();this.isDirty=!1},drawDataLabels:function(){},drawTracker:function(){},
animate:function(){}});la.ssgrid=pa;ma.bubble=Fa(ma.scatter,{states:{hover:{}}});pa=K.extendClass(la.scatter,{type:"bubble",drawPoints:function(){var a,d=this.data,b=this.chart,c,g,j,e,f,k,l=this.chart.plotWidth;c=this.chart.plotHeight;a=this.options.zMax;var i=this.options.bubbleScale,h,l=(l>c?c:l)/8;h=ab(a);if(this.options.marker.enabled)for(j=d.length;j--;)if(e=d[j],c=e.plotX,g=e.plotY,k=e.graphic,g!==ya&&!isNaN(g))a=e.pointAttr[e.selected?"select":""],f=ab(e.z),f=Aa(f*l/h)*i,a.r=f=f||0,k?k.animate({x:c,
y:g,r:f}):e.graphic=b.renderer.symbol(Ga(e.marker&&e.marker.symbol,this.symbol),c,g,f).attr(a).add(this.group)}});la.bubble=pa;ma.stepzoom=Fa(ma.line,{states:{hover:{}}});var Db=function(a,d,b){a<=0.01&&(a=0);var c=this.stepZoom,d=this.series,g=this.plotWidth,j=this.options._FCconf.clipExcessWidth,e=g/2,f=d.length,a=p(a,c.scrollPosition,0),k=c.scrollablePXLength*a,l=c.zoomHistory[c.currentZoomLevelIndex],i,h,q,m,n=this.plotLeft-k;c.catGroup.attr("translateX",n);c.catClipRect.attr("x",k-j/2);this.clipRect&&
this.clipRect.attr("x",k);for(j=f;j--;)if(f=d[j],f.group&&f.group.attr("translateX",n),f.dataLabelsGroup&&f.dataLabelsGroup.attr("translateX",n),f.clipRect&&f.clipRect.attr("x",k),b){c=ba.min(20,e);h=f.data;i=h.length;for(m=0;m<i;m+=1)q=h[m],q.y!==null&&q.tooltipPos&&(f=q.plotX-k,f>=0&&f<=e?f+=c:f>e&&f<=g&&(f-=c),q.tooltipPos[0]=f)}l.scrollPosition=a},pa=K.extendClass(la.line,{type:"stepzoom",translate:function(){for(var a=this.chart,d=this.options.stacking,b=this.xAxis.categories,c=this.yAxis,g=
this.data,j=g.length;j--;){var e=g[j],f=e.x,k=e.y,l=e.low,i=c.stacks[(k<0?"-":"")+this.stackKey];e.plotX=this.xAxis.translate(f);if(d&&i&&i[f]){var f=i[f],i=f.total,h=c.options.min,l=f.cum;f.cum+=k;k=ja(h,l+k);l=ja(h,l);d==="percent"&&(l=i?l*100/i:0,k=i?k*100/i:0);e.percentage=i?e.y*100/i:0;e.stackTotal=i}if(za(l))e.yBottom=c.translate(l,0,1,0,1);if(k!==null)e.plotY=c.translate(k,0,1,0,1);e.clientX=a.inverted?a.plotHeight-e.plotX:e.plotX;e.category=b&&b[e.x]!==ya?b[e.x]:e.x}},drawPoints:function(){var a=
this.options,d=this.chart,b=d.renderer,c=d.options.chart,g=d.stepZoom,j=a.dataLabels,e=+new Date,f=this.data,k=this.dataLabelsGroup,l=g.zoomHistory[g.currentZoomLevelIndex],i=l.perPointPixelDistance,h=g.scrollPosition*g.scrollablePXLength,g=l.stepping,l=l.seriesStart,a=a.marker.enabled,q=j.color,m=j.style,p=j.y===null,n=d.plotHeight,o=parseInt(m.fontSize,10),v=c.valuePadding,s=c.valuePosition,x,u,y,r,t,w,G,F,P,A,H,B,C,z=this.group,J=z.element;j.rotation=y=c.rotateValues==1?270:void 0;if(!k)k=this.dataLabelsGroup=
b.g("data-labels").attr({visibility:this.visible?ia:"hidden",zIndex:6}).translate(d.plotLeft-h,d.plotTop).add(),c.hasScroll&&k.clip(this.clipRect);c=k.element;q==="auto"&&(q=null);m.color=Ga(q,this.color);for(h=f.length;h--;)if(q=f[h],t=h-l,x=q.plotX=t*i,r=q.plotY,r!==ya&&!isNaN(r)&&(u=q.graphic,P=!(t<0||t%g!==0),t=j.align,w=(p?q.y>=0?-6:12:j.y)-v,G=j.formatter.call(q.getLabelConfig()),F=q.pointAttr[q.selected?"select":""],B=F.r,A=x+20,H=r-15,A=A<0?0:A,H=H<0?0:H,q.tooltipPos=[A,H],F.isTracker=e,a||
Na(F,{fill:Xa,stroke:Xa,r:3}),u?u.attr({x:x,y:r,r:B}):(q.graphic=u=d.renderer.symbol(Ga(q.marker&&q.marker.symbol,this.symbol),x,r,B).on(Wa?"touchstart":"mouseover",function(a){var b,c;if(b=(a.currentTarget?a.currentTarget:a.srcElement).point){c=b.series;C=a.relatedTarget||a.fromElement;if(d.hoverSeries!==c&&Ha(C,"isTracker")!==e)c.onMouseOver();b.onMouseOver()}}).on("mouseout",function(a){var b=a.currentTarget?a.currentTarget:a.srcElement;if((b=b.point&&b.point.series)&&!b.options.stickyTracking)if(C=
a.relatedTarget||a.toElement,Ha(C,"isTracker")!==e)b.onMouseOut()}).attr(F),P?(u.element.point=q,J.appendChild(u.element),u.added=!0):(u._parentNode=z,b.pending.push(u)),(!P||Ia&&J.gVis==="hidden")&&u.attr({visibility:"hidden"})),G!=null)){x+=j.x;u=r+w;switch(s){case "above":u=r+w;break;case "below":u=r-w+o;break;default:u=f[h-1],u=r+((u&&u.plotY)<=q.plotY?-(w-o):w)}u>n&&(u=r+w);u<o&&(u=r-w+o);if(r=q.dataLabel)r.attr({text:G}).animate({x:x,y:u});else if(G!==ya&&G!==null)r=q.dataLabel=b.text(G,x,u).css(m),
r.textStr!==void 0&&W&&b.buildText(r),P?(c.appendChild(r.element),r.added=!0,r.attr({align:t,rotation:y})):(r._parentNode=k,b.pending.push(r)),(!P||Ia&&c.gVis==="hidden")&&r.attr({visibility:"hidden"})}},drawGraph:function(){for(var a=this.options,d=this.chart,b=[],c=this.group,g=a.lineColor||this.color,j=a.lineWidth,e=a.dashStyle,f=d.renderer,k=this.data,l=a.connectNullData,i=d.stepZoom.zoomHistory[d.stepZoom.currentZoomLevelIndex],h,q=0,m=[],p=!0,n,o=(d.options.chart&&d.options.chart.stepZoom).skipOverlapPoints?
i.stepping:1,d=i.seriesStart;d<k.length;d+=o,q+=i.visiblePointDistance)h=k[d],za(h&&h.plotY)?(n&&(b.push(O,m[0],m[1],J),n=!1),p?(n=!0,p=!1,m[0]=q,m[1]=h.plotY):b.push(q,h.plotY)):l||(p=!0,n=!1);this.graphPath=b;this.singlePoints=[];k=this.graphLine;g={stroke:g,"stroke-width":j,"stroke-linecap":"round","stroke-linejoin":"round",dashstyle:e};k?this.graphLine.animate({d:b}):this.graphLine=f.path(b).attr(g).add(c).shadow(a.shadow,this.shadowGroup,a.shadow)},render:function(){var a=this,d=a.chart,b=d.stepZoom,
c=d.renderer,g=d.options.chart,j=g.stepZoom,e=d.options._FCconf,f=a.data,k;if(!d.stepZoom){var b=f.length-1,l=p(j.pixelsperpoint,30),i=p(j.displayStartIndex,0),h=p(j.displayEndIndex,b),q=d.plotWidth,m=d.plotLeft,n=j.scrollHeight,R=d.plotHeight+d.plotTop+p(j.scrollPadding,0),o=h-i,f=q/o,v=e.maxLabelWidth,s=e.numVisibleLabels,x=e.visibleLabelDistance,x=f<x?na(x/f):1,u=f<l?na(l/f):1,y,r;s&&(x=na((h+1-i)/s));f=q/(o-o%u);s=e.clipExcessWidth=v||0;o=i%u;y=b-b%u||1;v=(y-o)*f;r=q/v;k=v-q;v=k>0?(i-o)*f/(v-
q):0;g=g.plotBorderWidth;j=c.scroller(m-g,R,q+g+g,n,!0,{size:j.scrollBtnWidth,padding:j.scrollBtnPadding},e.flatScrollBars,e.scrollBar3DLighting).attr({fill:j.scrollColor}).setScrollRatio(r).callback(function(a,b,c){Db.call(d,a,b,c)}).add(d.seriesGroup);d.stepZoom=b={zoomHistory:[{seriesStart:o,seriesEnd:y,stepping:u,perPointPixelDistance:f,visiblePointDistance:u*f,seriesConf:[],scrollRatio:r,scrollPosition:v,scrollablePXLength:k}],currentZoomLevelIndex:0,pixelsPerPoint:l,displayStartIndex:i,displayEndIndex:h,
scrollRatio:1,maxIndex:b,scrollPosition:v,scrollablePXLength:k,scroller:j};g=a.xAxis;e=g.categories;i=g.options.labels;g=0;h=R+n;n=i.align;R=i.rotation;l=i.style;g=p(parseInt(l.lineHeight),12);b.catClipRect=c.clipRect(-(s/2),0,q+s,d.chartHeight);b.catGroup=h=c.g("category-labels").translate(m,h).clip(b.catClipRect).add(d.seriesGroup);u=b.catGroup.element;if(e&&e.length>0){q=b.catLabelArr=[];s=e.length;m=i.y||0;i=i.x||0;b.catLabelClipXDisplacement=-(g/2);b.xDisplacement=i;for(g=0;g<s;g+=1)if(r=g-o,
k=!(r<0||r%x!==0),y=e[g],za(y))r=r*f+i,y=q[g]=c.text(y,r,m).css(l),y.textStr!==void 0&&W&&c.buildText(y),k?(u.appendChild(y.element),y.added=!0):(y._parentNode=h,c.pending.push(y)),y.attr({align:n,rotation:R}),(!k||Ia&&u.gVis==="hidden")&&y.attr({visibility:"hidden"})}j.setScrollPosition(v)}var t,f=a.options,o=(x=(o=f.animation)&&a.animate)?o&&o.duration||500:0,w=a.clipRect,v=b.scrollPosition*b.scrollablePXLength;if(!w&&(w=a.clipRect=!d.hasRendered&&d.clipRect?d.clipRect:c.clipRect(v,0,d.plotSizeX,
d.plotSizeY),!d.clipRect))d.clipRect=w;if(!a.group)t=a.group=c.g("series"),t.clip(a.clipRect).attr({visibility:a.visible?ia:"hidden",zIndex:f.zIndex}).translate(d.plotLeft-v,d.plotTop).add(d.seriesGroup);x&&a.animate(!0);a.drawGraph&&a.drawGraph();a.drawPoints();x&&a.animate();setTimeout(function(){w.isAnimating=!1;if((t=a.group)&&w!==d.clipRect&&w.renderer)t.clip(a.clipRect=d.clipRect),w.destroy()},o);a.isDirty=!1}});la.stepzoom=pa;Na(K.Renderer.prototype.symbols,{pinModeIcon:function(a,d,b){d-=
1.5;var c=b*2/3,g=a-b,j=a+b,e=a-c,f=a+c,k=a+0.5,l=k+1,i=k+1.5,h=d-b,q=d+c,m=d-c,b=d+(b-c);return[O,g,h,J,e,m,e,b,g,q,a-0.5,q,a,d+d+0.5,k,q,j,q,f,b,f,m,j,h,i,h,i,m,i,b,l,b,l,m,i,m,i,h,M]},zoomOutIcon:function(a,d,b,c,g){a-=1;d-=1;var j=b-0.25,c=43*qa,e=48*qa,b=a+j*da(c),c=d+j*ca(c),f=a+j*da(e),e=d+j*ca(e),k=45*qa,l=b+4*da(k),i=c+4*ca(k),h=f+4*da(k),k=e+4*ca(k),g=g.getArcPath(a,d,b,c,f,e,j,j,0,1),j=["M",b,c],j=j.concat(g);return j=j.concat("Z","M",b+1,c+1,"L",l,i,h,k,f+1,e+1,"Z","M",a-2,d,"L",a+2,d,
"Z")},resetIcon:function(a,d,b,c,g){var c=a-b,j=(Ja+V)/2,e=a+b*da(j),j=d+b*ca(j),f=b*2/3;return[O,c,d].concat(g.getArcPath(a,d,c,d,e,j,b,b,1,1),[J,e+f,j-1,e+2,j+f-0.5,e,j])}});ma.pie3d=Fa(ma.pie,{states:{hover:{}}});var Ta=function(a,d){return ob(a[1]-(this.pageY||this.originalEvent&&this.originalEvent.pageY)+d.top,a[0]-(this.pageX||this.originalEvent&&this.originalEvent.pageX)+d.left)};Ea.prototype={parseColor:function(a,d){var b,c,g,j,e,f=d/2,k,l,i,h;this.use3DLighting?(b=sa(a,80),c=sa(a,75),g=
ka(a,85),j=ka(a,70),e=ka(a,40)):(b=sa(a,90),c=sa(a,87),g=ka(a,93),j=ka(a,87),e=ka(a,80));k=c+y+g+y+j+y+g+y+c;i=d+y+d+y+d+y+d+y+d;l=c+y+a+y+g+y+a+y+c;h=f+y+f+y+f+y+f+y+f;return{frontOuter:{FCcolor:{gradientUnits:"objectBoundingBox",x1:0,y1:0,x2:1,y2:0,color:k,alpha:i,angle:0,ratio:"0,25,5,5,65"}},backOuter:{FCcolor:{gradientUnits:"objectBoundingBox",x1:0,y1:0,x2:1,y2:0,color:c+y+a+y+e+y+a+y+c,alpha:h,angle:0,ratio:"0,62,8,8,22"}},frontInner:{FCcolor:{gradientUnits:"objectBoundingBox",x1:0,y1:0,x2:1,
y2:0,color:l,alpha:h,angle:0,ratio:"0,25,5,5,65"}},backInner:{FCcolor:{gradientUnits:"objectBoundingBox",x1:0,y1:0,x2:1,y2:0,color:k,alpha:i,angle:0,ratio:"0,62,8,8,22"}},top:W?{FCcolor:{gradientUnits:"objectBoundingBox",radialGradient:!0,cx:0.3,cy:0.95,r:1,color:j+y+g+y+c,alpha:d+y+d+y+d,ratio:"0,10,90"}}:{FCcolor:{gradientUnits:"objectBoundingBox",color:j+y+j+y+g+y+c,alpha:d+y+d+y+d+y+d,angle:-72,ratio:"0,8,15,77"}},bottom:aa(a,f),startSlice:aa(b,d),endSlice:aa(b,d)}},rotate:function(a){if(!this.hasOnePoint){for(var d=
this.pointElemStore,b=0,c=d.length,g;b<c;b+=1)g=d[b],g=g._confObject,g.start+=a,g.end+=a,this.updateSliceConf(g);this.refreshDrawing()}},refreshDrawing:function(){return function(){var a=this.slicingWallsArr,d=0,b,c=a.length,g,j=null,e=null,f,k=this.slicingWallsFrontGroup.element,l=this.slicingWallsBackGroup.element;a:{var i=a[0]&&a[0]._conf.index,h,q;f=i<=V;g=1;for(b=a.length;g<b;g+=1)if(q=a[g]._conf.index,h=q<=V,h!=f||q<i)break a;g=0}for(;d<c;d+=1,g+=1)g===c&&(g=0),b=a[g],f=b._conf.index,f<Ja?k.appendChild(b.element):
f<=V?(k.insertBefore(b.element,j),j=b.element):f<bb?(l.insertBefore(b.element,e),e=b.element):l.appendChild(b.element)}}(),updateSliceConf:function(a,d){var b=a.start,c=a.end,g=ua(b),j=ua(c),e,f,k,l,i,h,q,m,p,n,o,v,s,x,u,y,r=this.cx,t=this.cy,w=this.rx,G=this.ry,F=w+2,B=G+2,A=this.innerRx,H=this.innerRy,I=this.depth,C=this.depthY,z=this.renderer,K=a.elements,Q,D,T,N;f=da(g);k=ca(g);l=da(j);i=ca(j);h=r+w*f;q=t+G*k;m=r+F*f;p=t+B*k;Q=q+I;D=r+w*l;T=t+G*i;n=r+F*l;o=t+B*i;N=T+I;this.isDoughnut?(e=r+A*f,
v=t+H*k,u=v+I,s=r+A*l,x=t+H*i,y=x+I,a.startSlice=[O,h,q,J,h,Q,e,u,e,v,M],a.endSlice=[O,D,T,J,D,N,s,y,s,x,M]):(a.startSlice=[O,h,q,J,h,Q,r,C,r,t,M],a.endSlice=[O,D,T,J,D,N,r,C,r,t,M]);if(W){a&&a.clipTopPath?(a.clipTopPath[1]=m,a.clipTopPath[2]=p,a.clipTopPath[9]=n,a.clipTopPath[10]=o):a.clipTopPath=[O,m,p,ea,F,B,0,0,1,n,o,J,this.cx,this.cy,M];a.clipOuterFrontPath1=this.clipPathforNoClip;if(b!=c){if(g>j)if(g<V){if(a.clipOuterFrontPath1=[O,this.leftX,this.topY,J,h,this.topY,h,this.bottomY,this.leftX,
this.bottomY,M],a.clipOuterFrontPath=[O,D,this.topY,J,this.rightX,this.topY,this.rightX,this.bottomY,D,this.bottomY,M],a.clipOuterBackPath=this.clipPathforOuter,this.isDoughnut)a.clipInnerBackPath=this.clipPathforInner,a.clipInnerFrontPath=[O,this.leftInnerX,this.topY,J,e,this.topY,e,this.bottomY,this.leftInnerX,this.bottomY,M,O,s,this.topY,J,this.rightInnerX,this.topY,this.rightInnerX,this.bottomY,s,this.bottomY,M]}else if(j>V){if(a.clipOuterFrontPath=this.clipPathforOuter,a.clipOuterBackPath=[O,
this.rightX,this.topY,J,h,this.topY,h,this.bottomY,this.rightX,this.bottomY,M,O,D,this.topY,J,this.leftX,this.topY,this.leftX,this.bottomY,D,this.bottomY,M],this.isDoughnut)a.clipInnerBackPath=[O,this.rightInnerX,this.topY,J,e,this.topY,e,this.bottomY,this.rightInnerX,this.bottomY,M,O,s,this.topY,J,this.leftInnerX,this.topY,this.leftInnerX,this.bottomY,s,this.bottomY,M],a.clipInnerFrontPath=this.clipPathforInner}else{if(a.clipOuterFrontPath=[O,this.rightX,this.topY,J,D,this.topY,D,this.bottomY,this.rightX,
this.bottomY,M],a.clipOuterBackPath=[O,this.rightX,this.topY,J,h,this.topY,h,this.bottomY,this.rightX,this.bottomY,M],this.isDoughnut)a.clipInnerBackPath=[O,this.rightInnerX,this.topY,J,e,this.topY,e,this.bottomY,this.rightInnerX,this.bottomY,M],a.clipInnerFrontPath=[O,this.rightInnerX,this.topY,J,s,this.topY,s,this.bottomY,this.rightInnerX,this.bottomY,M]}else if(g<V)if(j>V){if(a.clipOuterFrontPath=[O,h,this.topY,J,this.leftX,this.topY,this.leftX,this.bottomY,h,this.bottomY,M],a.clipOuterBackPath=
[O,D,this.topY,J,this.leftX,this.topY,this.leftX,this.bottomY,D,this.bottomY,M],this.isDoughnut)a.clipInnerBackPath=[O,s,this.topY,J,this.leftInnerX,this.topY,this.leftInnerX,this.bottomY,s,this.bottomY,M],a.clipInnerFrontPath=[O,e,this.topY,J,this.leftInnerX,this.topY,this.leftInnerX,this.bottomY,e,this.bottomY,M]}else{if(a.clipOuterFrontPath=[O,h,this.topY,J,D,this.topY,D,this.bottomY,h,this.bottomY,M],a.clipOuterBackPath=this.clipPathforNoClip,this.isDoughnut)a.clipInnerBackPath=this.clipPathforNoClip,
a.clipInnerFrontPath=[O,e,this.topY,J,s,this.topY,s,this.bottomY,e,this.bottomY,M]}else if(a.clipOuterFrontPath=this.clipPathforNoClip,a.clipOuterBackPath=[O,h,this.topY,J,D,this.topY,D,this.bottomY,h,this.bottomY,M],this.isDoughnut)a.clipInnerBackPath=[O,e,this.topY,J,s,this.topY,s,this.bottomY,e,this.bottomY,M],a.clipInnerFrontPath=this.clipPathforNoClip;e=Ua(g,j);a.clipTopPath[7]=e>V?1:0}else a.clipOuterFrontPath=a.clipOuterBackPath=a.clipInnerBackPath=a.clipInnerFrontPath=this.clipPathforNoClip;
if(!d){a.elements.startSlice._conf.index=g;a.elements.endSlice._conf.index=j;a.elements.frontOuter._conf.index=La(j,g);if(a.elements.frontOuter1)a.elements.frontOuter1._conf.index=g,a.clipOuterFront1.attr({d:a.clipOuterFrontPath1});a.clipTop.attr({d:a.clipTopPath});a.clipOuterFront.attr({d:a.clipOuterFrontPath});a.clipOuterBack.attr({d:a.clipOuterBackPath});this.isDoughnut&&(a.clipInnerBack.attr({d:a.clipInnerBackPath}),a.clipInnerFront.attr({d:a.clipInnerFrontPath}));this.hasOnePoint?(a.elements.startSlice.hide(),
a.elements.endSlice.hide()):(a.elements.startSlice.attr({d:a.startSlice}).show(),a.elements.endSlice.attr({d:a.endSlice}).show())}}else{f=this.moveCmdArr;k=this.lineCmdArr;l=this.closeCmdArr;var S=this.centerPoint;i=this.leftPoint;m=this.topPoint;p=this.rightPoint;n=this.bottomPoint;var Z=this.leftDepthPoint,U=this.rightDepthPoint;o=this.leftInnerPoint;F=this.rightInnerPoint;B=this.leftInnerDepthPoint;I=this.rightInnerDepthPoint;a.outerFrontPath1=[];if(b!=c){if(g>j?g<V?(b=z.getArcPath(r,t,h,q,this.leftX,
t,w,G,1,0),c=z.getArcPath(r,t,this.leftX,t,this.rightX,t,w,G,1,0),T=z.getArcPath(r,t,this.rightX,t,D,T,w,G,1,0),a.outerBackPath=f.concat(i,c,k,U,z.getArcPath(r,C,this.rightX,C,this.leftX,C,w,G,0,0),l),a.outerFrontPath1=f.concat([h,q],b,k,Z,z.getArcPath(r,C,this.leftX,C,h,Q,w,G,0,0),l),a.outerFrontPath=f.concat(p,T,k,[D,N],z.getArcPath(r,C,D,N,this.rightX,C,w,G,0,0),l),a.topBorderPath=f.concat([h,q],b,c,T),this.isDoughnut?(h=z.getArcPath(r,t,s,x,this.rightInnerX,t,A,H,0,0),q=z.getArcPath(r,t,this.rightInnerX,
t,this.leftInnerX,t,A,H,0,0),v=z.getArcPath(r,t,this.leftInnerX,t,e,v,A,H,0,0),a.innerBackPath=f.concat(F,q,k,B,z.getArcPath(r,C,this.leftInnerX,C,this.rightInnerX,C,A,H,1,0),l),a.innerFrontPath=f.concat(o,v,k,[e,u],z.getArcPath(r,C,e,u,this.leftInnerX,C,A,H,1,0),l,f,[s,x],h,k,I,z.getArcPath(r,C,this.rightInnerX,C,s,y,A,H,1,0),l),a.topPath=a.topBorderPath.concat(k,[s,x],h,q,v,l),a.topBorderPath=a.topBorderPath.concat(f,[s,x],h,q,v)):a.topPath=a.topBorderPath.concat(k,S,l)):j>V?(b=z.getArcPath(r,t,
h,q,this.rightX,t,w,G,1,0),c=z.getArcPath(r,t,this.rightX,t,this.leftX,t,w,G,1,0),T=z.getArcPath(r,t,this.leftX,t,D,T,w,G,1,0),a.outerFrontPath=f.concat(p,c,k,Z,z.getArcPath(r,C,this.leftX,C,this.rightX,C,w,G,0,0),l),a.outerBackPath=f.concat([h,q],b,k,U,z.getArcPath(r,C,this.rightX,C,h,Q,w,G,0,0),l,f,i,T,k,[D,N],z.getArcPath(r,C,D,N,this.leftX,C,w,G,0,0),l),a.topBorderPath=f.concat([h,q],b,c,T),this.isDoughnut?(h=z.getArcPath(r,t,s,x,this.leftInnerX,t,A,H,0,0),q=z.getArcPath(r,t,this.leftInnerX,t,
this.rightInnerX,t,A,H,0,0),v=z.getArcPath(r,t,this.rightInnerX,t,e,v,A,H,0,0),a.innerFrontPath=f.concat(o,q,k,I,z.getArcPath(r,C,this.rightInnerX,C,this.leftInnerX,C,A,H,1,0),l),a.innerBackPath=f.concat(F,v,k,[e,u],z.getArcPath(r,C,e,u,this.rightInnerX,C,A,H,1,0),l,f,[s,x],h,k,B,z.getArcPath(r,C,this.leftInnerX,C,s,y,A,H,1,0),l),a.topPath=a.topBorderPath.concat(k,[s,x],h,q,v,l),a.topBorderPath=a.topBorderPath.concat(f,[s,x],h,q,v)):a.topPath=a.topBorderPath.concat(k,S,l)):(b=z.getArcPath(r,t,h,q,
this.rightX,t,w,G,1,0),c=z.getArcPath(r,t,this.rightX,t,D,T,w,G,1,0),a.outerFrontPath=f.concat(p,c,k,[D,N],z.getArcPath(r,C,D,N,this.rightX,C,w,G,0,0),l),a.outerBackPath=f.concat([h,q],b,k,U,z.getArcPath(r,C,this.rightX,C,h,Q,w,G,0,0),l),a.topBorderPath=f.concat([h,q],b,c),this.isDoughnut?(h=z.getArcPath(r,t,s,x,this.rightInnerX,t,A,H,0,0),q=z.getArcPath(r,t,this.rightInnerX,t,e,v,A,H,0,0),a.innerFrontPath=f.concat([s,x],h,k,I,z.getArcPath(r,C,this.rightInnerX,C,s,y,A,H,1,0),l),a.innerBackPath=f.concat(F,
q,k,[e,u],z.getArcPath(r,C,e,u,this.rightInnerX,C,A,H,1,0),l),a.topPath=a.topBorderPath.concat(k,[s,x],h,q,l),a.topBorderPath=a.topBorderPath.concat(f,[s,x],h,q)):a.topPath=a.topBorderPath.concat(k,S,l)):g<V?j>V?(b=z.getArcPath(r,t,h,q,this.leftX,t,w,G,1,0),c=z.getArcPath(r,t,this.leftX,t,D,T,w,G,1,0),a.outerBackPath=f.concat(i,c,k,[D,N],z.getArcPath(r,C,D,N,this.leftX,C,w,G,0,0),l),a.outerFrontPath=f.concat([h,q],b,k,Z,z.getArcPath(r,C,this.leftX,C,h,Q,w,G,0,0),l),a.topBorderPath=f.concat([h,q],
b,c),this.isDoughnut?(h=z.getArcPath(r,t,s,x,this.leftInnerX,t,A,H,0,0),q=z.getArcPath(r,t,this.leftInnerX,t,e,v,A,H,0,0),a.innerBackPath=f.concat([s,x],h,k,B,z.getArcPath(r,C,this.leftInnerX,C,s,y,A,H,1,0),l),a.innerFrontPath=f.concat(o,q,k,[e,u],z.getArcPath(r,C,e,u,this.leftInnerX,C,A,H,1,0),l),a.topPath=a.topBorderPath.concat(k,[s,x],h,q,l),a.topBorderPath=a.topBorderPath.concat(f,[s,x],h,q)):a.topPath=a.topBorderPath.concat(k,S,l)):(b=z.getArcPath(r,t,h,q,D,T,w,G,1,0),a.outerBackPath=f.concat([h,
q]),a.topBorderPath=a.outerBackPath.concat(b),a.outerFrontPath=a.topBorderPath.concat(k,[D,N],z.getArcPath(r,C,D,N,h,Q,w,G,0,0),l),this.isDoughnut?(h=z.getArcPath(r,t,s,x,e,v,A,H,0,0),a.innerBackPath=f.concat([s,x]),a.topPath=a.topBorderPath.concat(k,[s,x],h,l),a.topBorderPath=a.topBorderPath.concat(f,[s,x],h),a.innerFrontPath=a.innerBackPath.concat(h,k,[e,u],z.getArcPath(r,C,e,u,s,y,A,H,1,0),l)):a.topPath=a.topBorderPath.concat(k,S,l)):(b=z.getArcPath(r,t,h,q,D,T,w,G,1,0),a.outerFrontPath=f.concat([h,
q]),a.topBorderPath=a.outerFrontPath.concat(b),a.outerBackPath=a.topBorderPath.concat(k,[D,N],z.getArcPath(r,C,D,N,h,Q,w,G,0,0),l),this.isDoughnut?(h=z.getArcPath(r,t,s,x,e,v,A,H,0,0),a.innerFrontPath=f.concat([s,x]),a.topPath=a.topBorderPath.concat(k,[s,x],h,l),a.topBorderPath=a.topBorderPath.concat(a.innerFrontPath,h),a.innerBackPath=a.innerFrontPath.concat(h,k,[e,u],z.getArcPath(r,C,e,u,s,y,A,H,1,0),l)):a.topPath=a.topBorderPath.concat(k,S,l)),b=f.concat(i,k,p),h=f.concat(m,k,n),a.topPath=a.topPath.concat(b,
h),a.outerFrontPath=a.outerFrontPath.concat(b),a.outerFrontPath1=a.outerFrontPath1.concat(b),a.outerBackPath=a.outerBackPath.concat(b),this.isDoughnut)h=f.concat(o,k,F),a.innerFrontPath=a.innerFrontPath.concat(h),a.innerBackPath=a.innerBackPath.concat(h)}else if(a.topPath=a.outerFrontPath=a.outerBackPath=[],this.isDoughnut)a.innerFrontPath=a.innerBackPath=[];if(!d){a.elements.startSlice._conf.index=g;a.elements.endSlice._conf.index=j;a.elements.frontOuter._conf.index=La(j,g);if(a.elements.frontOuter1)a.elements.frontOuter1._conf.index=
g,K.frontOuter1.attr({d:a.outerFrontPath1});a.thisElement.attr({d:a.topPath});K.topBorder.attr({d:a.topBorderPath});K.bottom.attr({d:a.topPath});K.bottomBorder.attr({d:a.topBorderPath});K.frontOuter.attr({d:a.outerFrontPath});K.backOuter.attr({d:a.outerBackPath});this.isDoughnut&&(K.frontInner.attr({d:a.innerFrontPath}),K.backInner.attr({d:a.innerBackPath}));this.hasOnePoint?(a.elements.startSlice.hide(),a.elements.endSlice.hide()):(a.elements.startSlice.attr({d:a.startSlice}).show(),a.elements.endSlice.attr({d:a.endSlice}).show())}}},
createSlice:function(){var a={stroke:!0,strokeWidth:!0,"stroke-width":!0,dashstyle:!0,"stroke-dasharray":!0,translateX:!0,translateY:!0,"stroke-opacity":!0,fill:!0,opacity:!0,isTracker:!0,start:!0,end:!0},d=function(b,c){var d,g,i=this,h=i._confObject,j,m=h.elements,p,n,o=h.pie3DManager;typeof b==="string"&&za(c)&&(d=b,b={},b[d]=c);if(typeof b==="string")i=a[b]?h[b]:i._attr(b);else{for(d in b)if(g=b[d],a[d])if(h[d]=g,d==="translateX"||d==="translateY"||d==="isTracker"){j={};j[d]=g;for(p in m)m[p].attr(j);
i._attr(j)}else if(d==="stroke"||d==="strokeWidth"||d==="stroke-width"||d==="dashstyle"||d==="stroke-dasharray")j={},j[d]=g,m.topBorder.attr(j),m.startSlice.attr(j),m.endSlice.attr(j),m.bottomBorder.attr(j);else{if(d!=="fill"&&(d==="start"||d==="end"))n=!0}else i._attr(d,g);n&&(o.updateSliceConf(h),o.refreshDrawing())}return i},b=function(a,b){var c=this._confObject.elements,d;for(d in c)c[d].on(a,b);return this._on(a,b)},c=function(){var a=this._confObject.elements,b;for(b in a)a[b].hide();return this._hide()},
g=function(){var a=this._confObject.elements,b;for(b in a)a[b].show();return this._show()},j=function(){var a=this._confObject,b=a.elements,c;for(c in b)b[c].destroy();W&&(a.clipTop.destroy(),a.clipOuterFront.destroy(),a.clipOuterBack.destroy(),a.clipOuterFront1&&a.clipOuterFront1.destroy(),a.clipInnerFront&&a.clipInnerFront.destroy(),a.clipInnerBack&&a.clipInnerBack.destroy());return this._destroy()};return function(a,f,k,l,i,h,m){var p=this.renderer,k=this.parseColor(k,l),f={start:a,end:f,elements:{},
pie3DManager:this,topPath:this.topPath,topBorderPath:this.topBorderPath,outerFrontPath:this.outerFrontPath,outerFrontPath1:this.outerFrontPath,outerBackPath:this.outerBackPath,innerFrontPath:this.innerFrontPath,innerBackPath:this.innerBackPath},l=this.slicingWallsArr,n=f.elements;this.updateSliceConf(f,!0);a=p.path(f.topPath).attr({fill:k.top,"stroke-width":0}).add(this.topGroup);n.topBorder=p.path(f.topBorderPath).attr({stroke:i,"stroke-width":h}).add(this.topGroup);n.bottom=p.path(f.topPath).attr({fill:k.bottom,
"stroke-width":0}).add(this.bottomBorderGroup);n.bottomBorder=p.path(f.topBorderPath).attr({stroke:i,"stroke-width":h}).add(this.bottomBorderGroup);n.frontOuter=p.path(f.outerFrontPath).attr({fill:k.frontOuter,"stroke-width":0}).add(this.slicingWallsFrontGroup);n.backOuter=p.path(f.outerBackPath).attr({fill:k.backOuter,"stroke-width":0}).add(this.outerBackGroup);n.startSlice=p.path(f.startSlice).attr({fill:k.startSlice,stroke:i,"stroke-width":h}).add(this.slicingWallsFrontGroup);n.endSlice=p.path(f.endSlice).attr({fill:k.endSlice,
stroke:i,"stroke-width":h}).add(this.slicingWallsFrontGroup);i=ua(f.start);h=ua(f.end);if(Ua(i,h)>V){if(n.frontOuter1=p.path(f.outerFrontPath1).attr({fill:k.frontOuter,"stroke-width":0}).add(this.slicingWallsFrontGroup),l.push(n.startSlice,n.frontOuter1,n.frontOuter,n.endSlice),n.frontOuter1._conf={index:i,isStart:0.5,pIndex:m},W)f.clipOuterFront1=p.clipPath(f.clipOuterFrontPath1),n.frontOuter1.clip(f.clipOuterFront1)}else l.push(n.startSlice,n.frontOuter,n.endSlice);n.frontOuter._conf={index:La(h,
i),isStart:0.5,pIndex:m};n.startSlice._conf={index:i,isStart:0,pIndex:m};n.endSlice._conf={index:h,isStart:1,pIndex:m};this.hasOnePoint&&(n.startSlice.hide(),n.endSlice.hide());if(this.isDoughnut)n.frontInner=p.path(f.innerFrontPath).attr({fill:k.frontInner,"stroke-width":0}).add(this.innerFrontGroup),n.backInner=p.path(f.innerBackPath).attr({fill:k.backInner,"stroke-width":0}).add(this.innerBackGroup);if(W&&(f.clipTop=p.clipPath(f.clipTopPath),f.clipOuterFront=p.clipPath(f.clipOuterFrontPath),f.clipOuterBack=
p.clipPath(f.clipOuterBackPath),a.clip(f.clipTop),n.topBorder.clip(f.clipTop),n.bottom.clip(f.clipTop),n.bottomBorder.clip(f.clipTop),n.frontOuter.clip(f.clipOuterFront),n.backOuter.clip(f.clipOuterBack),this.isDoughnut))f.clipInnerFront=p.clipPath(f.clipInnerFrontPath),f.clipInnerBack=p.clipPath(f.clipInnerBackPath),n.frontInner.clip(f.clipInnerFront),n.backInner.clip(f.clipInnerBack);a._confObject=f;f.thisElement=a;a._destroy=a.destroy;a.destroy=j;a._show=a.show;a.show=g;a._hide=a.hide;a.hide=c;
a._on=a.on;a.on=b;a._attr=a.attr;a.attr=d;this.pointElemStore.push(a);return a}}()};Ea.prototype.constructor=Ea;K=K.extendClass(la.pie,{type:"pie3d",translate:function(){var a=0,d=this,b=d.options,c=n(this.chart.options.chart.startingAngle,0)%360,g=p(b.dataLabels.distance,20),j=d.slicedOffset=b.slicedOffset,e=wa([],b.center),f=d.chart,k=f.plotWidth,l=f.plotHeight,i,h,m,E=d.data,y,B=Ya(k,l),o,v,s,x=b.dataLabels.distance,u=d.pieYScale=b.pieYScale,J=d.pieSliceDepth=b.pieSliceDepth,r=d.managedPieSliceDepth=
b.managedPieSliceDepth,t=d.slicedOffsetY=j*u;e.push(b.size,b.innerSize||0);e=Oa(e,function(a,b){return(o=/%$/.test(a))?[k,l-r,B,B][b]*parseInt(a,10)/100:a});e[2]/=2;e[3]/=2;e.push(e[2]*u);e.push((e[2]+e[3])/2);e.push(e[5]*u);d.getX=function(a,b){m=ba.asin((a-e[1])/(e[2]+x));return e[0]+(b?-1:1)*da(m)*(e[2]+x)};d.center=e;ha(E,function(b){a+=b.y});d.labelsRadius=e[2]+g;d.labelsRadiusY=d.labelsRadius*u;d.quadrantHeight=(l-r)/2;d.quadrantWidth=k/2;var g=b.dataLabels,w=-c*qa,G,w=Aa(w*1E3)/1E3;G=w+oa;
c=p(parseInt(g.style.fontSize,10),10)+4;d.maxLabels=Math.floor(d.quadrantHeight/c);d.labelFontSize=c;d.connectorPadding=p(g.connectorPadding,5);d.isSmartLineSlanted=n(g.isSmartLineSlanted,!0);d.connectorWidth=p(g.connectorWidth,1);d.enableSmartLabels=g.enableSmartLabels;if(!d.pie3DManager)d.pie3DManager=new Ea(e[0],e[1],e[2],e[3],u,J,void 0,f.renderer,d.data.length===1,b.use3DLighting);ha(E,function(b){i=w;y=a?b.y/a:0;w=Aa((w+y*oa)*1E3)/1E3;w>G&&(w=G);h=w;b.shapeArgs={start:i,end:h};b.centerAngle=
m=(h+i)/2%oa;b.slicedTranslation=Oa([da(m)*j+f.plotLeft,ca(m)*t+f.plotTop],Aa);v=da(m)*e[2];d.radiusY=s=ca(m)*e[4];b.tooltipPos=[e[0]+v*0.7,e[1]+s];b.percentage=y*100;b.total=a});this.setTooltipPoints()},drawDataLabels:function(){var a=function(a,b){return a.point.y-b.point.y},d=function(a,b){return a.angle-b.angle},b=["left","left","right","right"],c=[-1,1,1,-1],g=[1,1,-1,-1];return function(j){var e=this.data,f,k,l=this.chart,i=l.options.instanceAPI.smartLabel,h=this.options.dataLabels;f=h.style;
var m=p(parseInt(f.lineHeight,10),12),n=h.placeInside,y=h.skipOverlapLabels,B=h.manageLabelOverflow,o=this.connectorPadding,v=this.connectorWidth,s,x=h.distance;Ga(h.softConnector,!0);var x=x>0,u,I=this.center,r=I[1],t=I[0],w=I[2],G=I[4],F=[[],[],[],[]],P,A=l.plotLeft,H=l.plotTop,l=l.plotSizeX,N,C,z,K,M,D,T,Q,S,Z=this.labelsRadius;u=this.labelsRadiusY;var U,X=this.labelFontSize,W=X,$=W/2,o=[o,o,-o,-o],aa=this.maxLabels,fa=this.isSmartLineSlanted,ga=this.enableSmartLabels,Y,ea=this.pieSliceDepth/2;
j||(kb.prototype.drawDataLabels.apply(this),i.setStyle(f));if(e.length==1){if(f=e[0],Y=f.dataLabel,f.slicedTranslation=[A,H],Y)Y.attr({visibility:ia,align:"center",x:t,y:r+$-2}),Y.x=t}else if(n)ha(e,function(a){if(Y=a.dataLabel){var b=a.centerAngle;S=r+I[6]*ca(b)+$-2;D=t+I[5]*da(b);Y.x=D;Y._x=D;Y.y=S;if(a.sliced){var b=a.slicedTranslation,c=b[1]-H;D+=b[0]-A;S+=c}Y.attr({visibility:ia,align:"center",x:D,y:S});a.dataLabelBG=Y.textBound()}});else{ha(e,function(a){if(Y=a.dataLabel){Y.on("click",function(b){a.firePointEvent("click",
b)});var b=a.centerAngle;b<0&&(b=oa+b);F[b<Ja?1:b<V?2:b<bb?3:0].push({point:a,angle:b})}});for(e=j=4;e--;){if(y&&(f=F[e].length-aa,f>0)){F[e].sort(a);U=F[e].splice(0,f);n=0;for(z=U.length;n<z;n+=1)f=U[n].point,f.dataLabel.attr({visibility:"hidden"}),f.connector&&f.connector.attr({visibility:"hidden"})}F[e].sort(d)}e=ja(F[0].length,F[1].length,F[2].length,F[3].length);U=ja(Ya(e,aa)*W,u);F[1].reverse();for(F[3].reverse();j--;){n=F[j];z=n.length;y||(W=z>aa?U/z:X,$=W/2);f=z*W-$;u=U+$;for(e=0;e<z;e+=1,
f-=W)s=Za(U*ca(n[e].angle)),u-s<W?s=u-W:s<f&&(s=f),u=n[e].oriY=s;P=b[j];z=U-z*W+$;u=-$;for(e=n.length-1;e>=0;e-=1,z+=W){f=n[e].point;k=n[e].angle;K=f.sliced;Y=f.dataLabel;s=Za(U*ca(k));s-u<W?s=u+W:s>z&&(s=z);u=s;T=(s+n[e].oriY)/2;s=t+g[j]*Z*da(ba.asin(T/U));T*=c[j];T+=r;Q=r+G*ca(k);M=t+w*da(k);D=s+o[j];S=T+$-2;Y.x=D;Y._x=D;if(B)N=j>1?D:l-D,C=Y._str=Y._str||Y.textStr||Y.element&&Y.element.innerHTML,Y.attr({text:i.getSmartText(C,N,m).text});k<V&&(T+=ea,Q+=ea,S+=ea);Y.y=S;if(K)K=f.slicedTranslation,
k=K[0]-A,K=K[1]-H,D+=k,s+=k,M+=k,Q+=K;Y.attr({visibility:ia,align:P,x:D,y:S});f.dataLabelBG=Y.textBound();if(x&&v&&ga)k=f.connector,f.connectorPath=s=[O,M,Q,J,fa?s:M,T,D,T],k?(k.attr({d:s}),k.attr("visibility",ia)):f.connector=k=this.chart.renderer.path(s).attr({"stroke-width":v,stroke:h.connectorColor||"#606060",visibility:ia,zIndex:3}).translate(A,H).add().on("click",function(a){return function(b){a.firePointEvent("click",b)}}(f))}}}}}(),rotate:function(a){var d=this.data,b=this.slicedOffset,c=
this.slicedOffsetY,g=this.chart.plotLeft,j=this.chart.plotTop,e=p(this.chart.options.chart.startingAngle,0),f,k=this.center;f=(a-e)%360;this.chart.options.chart.startingAngle=p(a,this.chart.options.chart.startingAngle)%360;f=f*$a/180;this.pie3DManager&&this.pie3DManager.rotate(f);ha(d,function(a){var d=a.graphic,e=a.shapeArgs,e={start:e.start+=f,end:e.end+=f},m=a.centerAngle=ua((e.start+e.end)/2),e=a.sliced,n=da(m),m=ca(m);a.slicedTranslation=Oa([n*b+g,m*c+j],Aa);a.tooltipPos=[k[0]+n*k[2]*0.7,k[1]+
m*k[4]];d&&e&&a.graphic.attr({translateX:a.slicedTranslation[0],translateY:a.slicedTranslation[1]})});this.drawDataLabels(!0)},drawPoints:function(){var a=this,d=a.chart,b,c;ha(a.data,function(g,j){var e=g.sliced,f=g.slicedTranslation;b=g.graphic;c=g.shapeArgs;b?b.animate(c):(g.graphic=a.pie3DManager.createSlice(c.start,c.end,g.color,g._3dAlpha,g.borderColor,g.borderWidth,j),g.graphic.translate(e?f[0]:d.plotLeft,e?f[1]:d.plotTop));g.visible===!1&&g.setVisible(!1)});a.pie3DManager.refreshDrawing()},
drawTracker:function(){var a=this,d=a.chart,b=+new Date,c=a.options,g,j=[a.center[0]+a.chart.plotLeft,a.center[1]+a.chart.plotTop],e,f=a.options.enableRotation,k,l,i,h,m;f&&(k=function(b){e=mb(a.chart.container);a.rotationStartInstanceAngle=Ta.call(b,j,e)-a.chart.options.chart.startingAngle*qa;a.chart.tooltip&&(b.type==="dragstart"?a.chart.tooltip.block(!0):(a.chart.tooltip.block(!1),a.chart.tooltip.refresh(b.data,!0)))});ha(a.data,function(n){if(n.y!==null){if(n.link!==void 0)var p={cursor:"pointer",
_cursor:"hand"};i=n.graphic;i.attr({isTracker:b});i.on(Wa?"touchstart":"mouseover",function(c){g=c.relatedTarget||c.fromElement;if(d.hoverSeries!==a&&Ha(g,"isTracker")!==b)a.onMouseOver();n.onMouseOver()}).on("mouseout",function(d){if(!c.stickyTracking&&(g=d.relatedTarget||d.toElement,Ha(g,"isTracker")!==b))a.onMouseOut()}).css(p);if(f){l=i._confObject;h=l.elements;for(m in h)xa(h[m].element,"dragstart dragend",k,n),xa(h[m].element,"drag",function(b){a.rotate((Ta.call(b,j,e)-a.rotationStartInstanceAngle)/
qa)});xa(i.element,"dragstart dragend",k,n);xa(i.element,"drag",function(b){a.rotate((Ta.call(b,j,e)-a.rotationStartInstanceAngle)/qa)})}}})}});la.pie3d=K},[3,2,2,"sr4"]]);
